"""French + English translations.

French is the default (target audience: Guinea mining site). Keys follow the
batmex_web convention: dotted namespaces (section.key).

Anything missing from a non-default language falls back through `get_t`'s
chained lookup in app.py.
"""

TRANSLATIONS = {
    # ── French (default) ──────────────────────────────────────────────────
    "fr": {
        # Brand
        "app.title": "Zone Web",
        "app.tagline": "Suivi de flotte",

        # Auth
        "auth.login":             "Connexion",
        "auth.logout":            "Déconnexion",
        "auth.username":          "Nom d'utilisateur",
        "auth.email":             "Courriel",
        "auth.email_optional":    "Courriel (facultatif)",
        "auth.password":          "Mot de passe",
        "auth.sign_in":           "Se connecter",
        "auth.invalid_credentials": "Identifiants invalides.",
        "auth.required":          "Veuillez vous connecter.",

        # Dashboard
        "dash.welcome":   "Bienvenue",
        "dash.super_sub": "Super admin — accès complet à la configuration et à toutes les flottes.",
        "dash.month_spend":      "Dépenses du mois",
        "dash.pending":          "À valider",
        "dash.open_alerts":      "Alertes ouvertes",
        "dash.recent_activity":  "Activité récente",
        "dash.no_alerts":        "Aucune alerte ouverte. Tout est en ordre.",
        "dash.no_activity":      "Aucune saisie récente.",
        "dash.view_all":         "Tout voir",
        "dash.spend_trend":      "Évolution des dépenses",
        "dash.last_6_months":    "6 derniers mois",
        "dash.spend_by_cat":     "Dépenses par catégorie",
        # Tableau de bord opérationnel
        "dash.month_hours":      "Heures travaillées (mois)",
        "dash.month_trips":      "Voyages (mois)",
        "dash.month_km":         "Kilomètres (mois)",
        "dash.month_liters":     "Carburant (mois)",
        "dash.active_vehicles":  "Véhicules actifs ce mois",
        "dash.activity_trend":   "Activité mensuelle",
        "dash.top_vehicles":     "Véhicules les plus actifs",
        "dash.daily_entries":    "Saisies par jour",
        "dash.fuel_trend":       "Consommation de carburant",
        "dash.entries":          "Saisies",
        "dash.this_month":       "Ce mois",
        "dash.last_30_days":     "30 derniers jours",

        # First-login welcome guide
        "tour.title":   "Guide de démarrage",
        "tour.hello":   "Bienvenue",
        "tour.intro":   "Voici, dans l'ordre, les étapes pour bien utiliser la plateforme.",
        "tour.go":      "Ouvrir",
        "tour.start":   "Commencer",
        "tour.close":   "Fermer le guide",
        "tour.replay":  "Revoir le guide",
        "tour.replay_hint": "Vous pourrez le revoir à tout moment.",
        "tour.fleets.t":    "Créer vos flottes (clients)",
        "tour.fleets.d":    "Une flotte par client ; cochez ses types de machines et fixez les tarifs.",
        "tour.operators.t": "Ajouter les conducteurs",
        "tour.operators.d": "Les chauffeurs de chaque flotte.",
        "tour.vehicles.t":  "Ajouter les véhicules",
        "tour.vehicles.d":  "Catégorie, flotte et conducteur par défaut.",
        "tour.users.t":     "Créer les utilisateurs",
        "tour.users.d":     "Le personnel et ses accès par flotte.",
        "tour.rules.t":     "Définir les règles d'entretien",
        "tour.rules.d":     "Les seuils en km, heures ou jours.",
        "tour.entry.t":     "Faire la saisie quotidienne",
        "tour.entry.d":     "Chaque jour : activité, km et conducteur par véhicule.",
        "tour.carburant.t": "Suivre le carburant",
        "tour.carburant.d": "Créez vos citernes, puis notez ce que chaque machine y prend.",
        "tour.expense.t":   "Enregistrer les dépenses",
        "tour.expense.d":   "Le carburant et les autres coûts.",
        "tour.maint.t":     "Enregistrer les entretiens",
        "tour.maint.d":     "Un entretien réalisé résout son alerte.",
        "tour.alerts.t":    "Suivre les alertes",
        "tour.alerts.d":    "Les entretiens à venir ou en retard.",
        "tour.dashboard.t": "Consulter le tableau de bord",
        "tour.dashboard.d": "La vue d'ensemble en un coup d'œil.",
        "tour.insights.t":  "Analyser",
        "tour.insights.d":  "Carburant vs référence, coûts, véhicules inactifs.",
        "tour.invoicing.t": "Facturer les clients",
        "tour.invoicing.d": "Unités travaillées × tarif, par mois.",

        # Nav
        "nav.dashboard":            "Tableau de bord",
        "nav.vehicles":             "Véhicules",
        "nav.operators":            "Conducteurs",
        "nav.roster":               "Pointage",
        "nav.daily_entries":        "Saisie quotidienne",
        "nav.maintenance":          "Maintenance",
        "nav.maintenance_records":  "Historique entretien",
        "nav.maintenance_rules":    "Règles d'entretien",
        "nav.alerts":               "Alertes",
        "nav.expenses":             "Dépenses",
        "nav.insights":             "Analyse",
        "nav.invoicing":            "Facturation",
        "nav.reports":              "Rapports",
        "nav.management":           "Gestion",
        "nav.validation":           "Validation",
        "nav.approvals":            "Validations en attente",
        "nav.my_requests":          "Mes demandes",
        "nav.help":                 "Aide",
        "help.toc":                 "Sommaire",
        "help.note":                "À noter",
        "help.print":               "Imprimer",
        "nav.admin":                "Administration",
        "nav.change_password":      "Changer le mot de passe",

        # Operations insights
        "insights.fleet_total":   "Coût total du parc",
        "insights.over_baseline": "Véhicules hors-norme (carburant)",
        "insights.idle_count":    "Véhicules inactifs",
        "insights.fuel_title":    "Carburant : réel vs. référence",
        "insights.fuel_hint":     "Consommation réelle comparée à la référence (activité × litres attendus).",
        "insights.fuel_empty":    "Pas assez de données : il faut une référence de consommation, de l'activité et des pleins sur la période.",
        "insights.activity":      "Activité",
        "insights.expected_l":    "Attendu",
        "insights.actual_l":      "Réel",
        "insights.variance":      "Écart",
        "insights.cost_title":    "Coût par véhicule",
        "insights.other":         "Autre",
        "insights.total":         "Total",
        "insights.per_unit":      "Coût unitaire",
        "insights.per_km":        "Coût/km",
        "insights.cost_note":     "Coût = carburant + entretien + autres dépenses, sur la période.",
        "insights.idle_title":    "Véhicules inactifs / sous-utilisés",
        "insights.idle_hint":     "Signalés après %d jours sans saisie.",
        "insights.last_activity": "Dernière activité",
        "insights.days_idle":     "Jours sans activité",
        "insights.idle_badge":    "Inactif",
        "insights.never":         "Jamais",
        "insights.idle_empty":    "Aucun véhicule actif.",

        # Password change
        "pw.title":                  "Changement de mot de passe",
        "pw.error.wrong_current":    "Le mot de passe actuel est incorrect.",
        "pw.error.too_short":        "Le nouveau mot de passe doit contenir au moins 6 caractères.",
        "pw.error.no_match":         "Les deux nouveaux mots de passe ne correspondent pas.",
        "pw.success":                "Mot de passe mis à jour.",
        "form.current_password":     "Mot de passe actuel",
        "form.new_password":         "Nouveau mot de passe",
        "form.confirm_password":     "Confirmer le nouveau mot de passe",
        "form.update_password":      "Mettre à jour le mot de passe",

        # Admin
        "admin.users":      "Utilisateurs",
        "admin.fleets":     "Flottes",
        "admin.roles":      "Rôles",
        "admin.categories": "Catégories de véhicules",
        "admin.settings":   "Paramètres",
        "admin.audit_log":  "Journal d'activité",

        # Activity log viewer
        "audit.entries":       "entrées",
        "audit.timestamp":     "Horodatage",
        "audit.user":          "Utilisateur",
        "audit.action":        "Action",
        "audit.resource":      "Ressource",
        "audit.detail":        "Détail",
        "audit.ip":            "IP",
        "audit.search_user":   "Rechercher un utilisateur",
        "audit.all_actions":   "Toutes les actions",
        "audit.all_resources": "Toutes les ressources",
        "audit.all_fleets":    "Toutes les flottes",
        "audit.empty":         "Aucune entrée dans le journal.",
        "audit.prev":          "Précédent",
        "audit.next":          "Suivant",
        "audit.page":          "Page",

        # Settings
        "setting.cat.approval":      "Validation",
        "setting.cat.general":       "Général",
        "setting.grace_period_minutes": "Délai de grâce pour les auto-corrections (minutes)",
        "setting.currency":          "Devise par défaut",
        "setting.default_lang":      "Langue par défaut",
        "setting.lang.fr":           "Français",
        "setting.lang.en":           "Anglais",
        "setting.updated":           "Modifié le",
        "setting.saved":             "Paramètres enregistrés.",
        "setting.err.number":        "Valeur numérique invalide.",
        "setting.err.range":         "Valeur hors limites.",
        "setting.err.choice":        "Choix invalide.",

        # Fleets
        "fleet.new":            "Nouvelle flotte",
        "fleet.edit":           "Modifier la flotte",
        "fleet.name":           "Nom",
        "fleet.name_hint":      "ex. Transport personnel",
        "fleet.slug":           "Identifiant (slug)",
        "fleet.slug_hint":      "généré automatiquement si laissé vide",
        "fleet.description":    "Description",
        "fleet.categories":     "Catégories de véhicules",
        "fleet.rates_hint":     "Cochez les types de machines de ce client et fixez le tarif facturé par unité travaillée.",
        "fleet.categories_hint": "Cochez les types de machines exploités par ce client.",
        "fleet.rate_ph":        "Tarif",
        "fleet.rate_effective_from": "Tarifs applicables à partir du",
        "fleet.rate_effective_hint": "Un changement de tarif crée une nouvelle valeur datée (l'historique est conservé).",
        "fleet.err.bad_rate":   "Tarif invalide.",
        "fleet.vehicles":       "Véhicules",
        "fleet.users":          "Utilisateurs",

        # Invoicing / facturation
        "invoicing.client":       "Client",
        "invoicing.units":        "Unités travaillées",
        "invoicing.rate":         "Tarif",
        "invoicing.amount":       "Montant",
        "invoicing.total_client": "Total à facturer",
        "invoicing.no_rate":      "tarif manquant",
        "invoicing.missing_rate_warn": "Certaines saisies n'ont pas de tarif défini pour leur date — le montant correspondant n'est pas facturé. Définissez le tarif sur la fiche flotte.",
        "invoicing.note":         "Montant = unités travaillées × tarif en vigueur à la date de chaque saisie.",
        "invoicing.empty":        "Aucune activité facturable pour ce client sur ce mois.",
        "fleet.empty":          "Aucune flotte pour le moment.",
        "fleet.created":        "Flotte créée.",
        "fleet.updated":        "Flotte mise à jour.",
        "fleet.deleted":        "Flotte supprimée.",
        "fleet.delete_confirm": "Supprimer cette flotte ?",
        "fleet.err.name_required": "Le nom est obligatoire.",
        "fleet.err.name_taken":    "Une flotte porte déjà ce nom.",
        "fleet.err.slug_taken":    "Cet identifiant (slug) est déjà utilisé.",
        "fleet.err.delete_blocked": "Impossible de supprimer : des véhicules, conducteurs ou utilisateurs sont encore rattachés à cette flotte.",

        # Vehicles
        "vehicle.new":            "Nouveau véhicule",
        "vehicle.edit":           "Modifier le véhicule",
        "vehicle.all":            "Tous",
        "vehicle.code":           "Code / Immatriculation",
        "vehicle.category":       "Catégorie",
        "vehicle.fleet":          "Flotte",
        "vehicle.site":           "Site",
        "vehicle.description":    "Description",
        "vehicle.default_operator":      "Conducteur par défaut",
        "vehicle.default_operator_hint": "Facultatif — pré-rempli à la saisie quotidienne. Choisi parmi les conducteurs enregistrés de la flotte.",
        "vehicle.no_default_operator":   "Aucun",
        "vehicle.err.operator_fleet":    "Le conducteur par défaut doit appartenir à la flotte du véhicule.",
        "vehicle.baseline":       "Consommation de référence",
        "vehicle.baseline_override": "Consommation (L/unité)",
        "vehicle.baseline_hint":  "Laisser vide pour utiliser la valeur par défaut de la catégorie.",
        "vehicle.cost_override":  "Coût par unité (GNF)",
        "vehicle.cost_hint":      "Laisser vide pour utiliser la valeur par défaut de la catégorie.",
        "vehicle.active":         "Actif",
        "vehicle.inactive":       "Inactif",
        "vehicle.is_active":      "Véhicule actif",
        "vehicle.status":         "Statut",
        "vehicle.from_category":  "valeur de la catégorie",
        "vehicle.empty":          "Aucun véhicule pour le moment.",
        "vehicle.created":        "Véhicule créé.",
        "vehicle.updated":        "Véhicule mis à jour.",
        "vehicle.deleted":        "Véhicule supprimé.",
        "vehicle.submitted":      "Modification soumise pour validation.",
        "vehicle.delete_confirm": "Supprimer ce véhicule ?",
        "vehicle.err.code_required":     "Le code du véhicule est obligatoire.",
        "vehicle.err.fleet_required":    "Veuillez choisir une flotte.",
        "vehicle.err.category_required": "Veuillez choisir une catégorie.",
        "vehicle.err.code_taken":        "Ce code de véhicule existe déjà.",
        "vehicle.err.cat_not_in_fleet":  "Cette catégorie n'appartient pas à la flotte choisie.",
        "vehicle.err.bad_number":        "Valeur numérique invalide.",
        "vehicle.err.delete_blocked":    "Impossible de supprimer : des saisies, entretiens ou dépenses sont rattachés à ce véhicule.",

        # Operators (drivers)
        "operator.new":            "Nouveau conducteur",
        "operator.edit":           "Modifier le conducteur",
        "operator.all":            "Tous",
        "operator.name":           "Nom",
        "operator.fleet":          "Flotte",
        "operator.phone":          "Téléphone",
        "operator.license":        "N° de permis",
        "operator.notes":          "Notes",
        "operator.active":         "Actif",
        "operator.inactive":       "Inactif",
        "operator.is_active":      "Conducteur actif",
        "operator.status":         "Statut",
        "operator.last_activity":  "Dernier pointage",
        "operator.activity":       "Activité",
        "operator.kpi.pointages":  "Pointages",
        "operator.kpi.hours":      "Heures",
        "operator.kpi.trips":      "Voyages",
        "operator.kpi.km":         "Kilomètres",
        "operator.expenses":       "Dépenses",
        "operator.expenses_hint":  "Dépenses et entretiens attribués à ce conducteur, par mois et par catégorie.",
        "operator.exp_maintenance": "Entretien",
        "operator.no_expenses":    "Aucune dépense sur cette période.",
        "operator.vehicles":       "Véhicules conduits",
        "operator.default_badge":  "Par défaut",
        "operator.no_vehicles":    "Aucun véhicule associé.",
        "operator.records":        "Entretiens associés",
        "operator.no_records":     "Aucun entretien associé.",
        "operator.empty":          "Aucun conducteur pour le moment.",
        "operator.created":        "Conducteur créé.",
        "operator.updated":        "Conducteur mis à jour.",
        "operator.deleted":        "Conducteur supprimé.",
        "operator.submitted":      "Modification soumise pour validation.",
        "operator.delete_confirm": "Supprimer ce conducteur ?",
        "operator.err.name_required":  "Le nom est obligatoire.",
        "operator.err.fleet_required": "Veuillez choisir une flotte.",
        "operator.err.name_taken":     "Un conducteur porte déjà ce nom dans cette flotte.",

        # Daily entries
        "entry.new":            "Nouvelle saisie",
        "entry.edit":           "Modifier la saisie",
        "entry.add":            "Ajouter",
        "entry.vehicle":        "Véhicule",
        "entry.date":           "Date",
        "entry.trips":          "Voyages",
        "entry.hours":          "Heures",
        "entry.index_start":    "Index début",
        "entry.index_end":      "Index fin",
        "entry.hours_auto":     "Heures (auto)",
        "entry.err.index_order": "L'index de fin doit être supérieur ou égal à l'index de début.",
        "entry.fuel":           "Carburant (L)",
        "entry.km":             "Kilométrage",
        "entry.operator":       "Conducteur",
        "entry.note":           "Note",
        "entry.activity":       "Activité",
        "entry.all_vehicles":   "Tous les véhicules",
        "entry.all_fleets":     "Toutes les flottes",
        "entry.all_operators":  "Tous les conducteurs",
        "entry.all_categories": "Toutes les catégories",
        "entry.month":          "Mois",
        "entry.or":             "ou",
        "entry.filter":         "Filtrer",
        "entry.more_filters":   "Plus de filtres",
        "entry.from":           "Du",
        "entry.to":             "Au",
        "entry.clear":          "Réinitialiser",
        "entry.empty":          "Aucune saisie pour le moment.",
        "entry.created":        "Saisie enregistrée.",
        "entry.updated":        "Saisie mise à jour.",
        "entry.deleted":        "Saisie supprimée.",
        "entry.submitted":      "Saisie soumise pour validation.",
        "entry.err.pending_exists": "Une demande est déjà en attente pour cette saisie ; elle doit d'abord être traitée.",
        "entry.delete_confirm": "Supprimer cette saisie ?",
        "entry.err.vehicle_required": "Veuillez choisir un véhicule.",
        "entry.err.date_required":    "Date invalide.",
        "entry.err.bad_number":       "Valeur numérique invalide.",
        "entry.err.negative":         "Les valeurs ne peuvent pas être négatives.",

        # Roster (pointage)
        "roster.prev_day":   "Jour précédent",
        "roster.next_day":   "Jour suivant",
        "roster.done":       "faits",
        "roster.pending":    "en attente",
        "roster.tap_to_log": "Appuyer pour saisir",
        "roster.no_vehicles": "Aucun véhicule actif dans cette flotte.",
        "roster.no_fleet":   "Aucune flotte accessible. Demandez l'accès à une flotte.",

        # Expenses
        "expense.new":            "Nouvelle dépense",
        "expense.edit":           "Modifier la dépense",
        "expense.add":            "Ajouter",
        "expense.all":            "Toutes",
        "expense.category":       "Catégorie",
        "expense.date":           "Date",
        "expense.fleet":          "Flotte",
        "expense.vehicle":        "Véhicule",
        "expense.fleet_wide":     "Dépense de flotte",
        "expense.target":         "Véhicule / Flotte",
        "expense.amount":         "Montant (GNF)",
        "expense.liters":         "Litres",
        "expense.operator":       "Conducteur (optionnel)",
        "expense.supplier":       "Fournisseur",
        "expense.description":    "Description",
        "expense.total":          "Total : ",
        "expense.count":          "dépenses",
        "expense.empty":          "Aucune dépense pour le moment.",
        "expense.created":        "Dépense enregistrée.",
        "expense.updated":        "Dépense mise à jour.",
        "expense.deleted":        "Dépense supprimée.",
        "expense.submitted":      "Dépense soumise pour validation.",
        "expense.delete_confirm": "Supprimer cette dépense ?",
        "expense.err.category_required": "Veuillez choisir une catégorie.",
        "expense.err.fleet_required":    "Veuillez choisir une flotte.",
        "expense.err.vehicle_fleet":     "Le véhicule n'appartient pas à la flotte choisie.",
        "expense.err.vehicle_required":  "Veuillez choisir un véhicule.",
        "expense.err.label_required":    "Veuillez donner un nom à la dépense.",
        "expense.err.payment_required":  "Veuillez choisir un moyen de paiement.",
        "expense.err.maintenance_locked": "Cette dépense provient d'un entretien : modifiez-la depuis la fiche d'entretien.",
        "expense.err.date_required":     "Date invalide.",
        "expense.err.amount_required":   "Montant invalide.",
        "expense.err.bad_number":        "Valeur numérique invalide.",
        # Dépenses — véhicule ou générale
        "expense.is_vehicle":     "Cette dépense concerne un véhicule",
        "expense.label":          "Nom de la dépense",
        "expense.company":        "Dépense de société",
        "expense.filter.general": "Générales",
        "expense.from_maint":     "Issue d'un entretien",
        # Paiement
        "expense.payment_method":    "Moyen de paiement",
        "expense.payment_reference": "Référence (optionnel)",
        "pay.mobile_money": "Mobile Money",
        "pay.cash":         "Espèces",
        "pay.transfer":     "Virement bancaire",
        "pay.cheque":       "Chèque",
        "pay.other":        "Autre",
        # Carburant
        "nav.fuel":          "Carburant",
        "fuel.new":          "Nouveau plein",
        "citerne.new":          "Nouvelle citerne",
        "citerne.edit":         "Modifier la citerne",
        "citerne.code":         "Code",
        "citerne.name":         "Nom",
        "citerne.fleet":        "Flotte",
        "citerne.capacity":     "Capacité (litres)",
        "citerne.stock":        "Stock actuel",
        "citerne.initial":      "Stock initial (litres)",
        "citerne.initial_hint": "Le carburant déjà présent dans la citerne. Les rentrées chez le client viendront à l'étape suivante.",
        "citerne.created":      "Citerne créée.",
        "citerne.updated":      "Citerne mise à jour.",
        "citerne.archived":     "Citerne archivée.",
        "citerne.reactivated":  "Citerne réactivée.",
        "citerne.empty":        "Aucune citerne. Créez-en une pour commencer.",
        "citerne.err.code":         "Le code est obligatoire.",
        "citerne.err.name":         "Le nom est obligatoire.",
        "citerne.err.capacity":     "La capacité doit être positive.",
        "citerne.err.fleet":        "La flotte est obligatoire.",
        "citerne.err.over_capacity":"Le stock dépasse la capacité.",
        "citerne.err.code_taken":   "Ce code est déjà utilisé.",
        "distribution.new":         "Prise de carburant",
        "distribution.recent":      "Prises récentes",
        "distribution.date":        "Date",
        "distribution.machine":     "Machine",
        "distribution.citerne":     "Citerne source",
        "distribution.liters":      "Litres pris",
        "distribution.driver":      "Conducteur",
        "distribution.available":   "dispo",
        "distribution.created":     "Prise de carburant enregistrée.",
        "distribution.deleted":     "Prise supprimée.",
        "distribution.delete_confirm": "Supprimer cette prise ? Le stock de la citerne sera recrédité.",
        "distribution.err.date":        "Date invalide.",
        "distribution.err.citerne":     "Choisissez une citerne active.",
        "distribution.err.vehicle":     "Choisissez une machine.",
        "distribution.err.fleet_mismatch": "La machine et la citerne doivent être de la même flotte.",
        "distribution.err.liters":      "Litres invalides.",
        "distribution.err.stock":       "Stock insuffisant dans la citerne.",
        "fuel.empty":        "Aucun plein enregistré.",
        "fuel.liters":       "Litres",
        "fuel.total_liters": "Total litres",
        "fuel.price_per_l":  "Prix / litre",
        "fuel.station":      "Station / Fournisseur",
        "expense.cat.fuel":       "Carburant",
        "expense.cat.vidange":    "Vidange",
        "expense.cat.filtre":     "Filtres",
        "expense.cat.pneus":      "Pneus",
        "expense.cat.reparation": "Réparation",
        "expense.cat.piece":      "Pièces détachées",
        "expense.cat.assurance":  "Assurance",
        "expense.cat.accident":   "Accident",
        "expense.cat.lavage":     "Lavage",
        "expense.cat.agent":      "Frais d'agent",
        "expense.cat.autre":      "Autre",
        "expense.cat.entretien":  "Entretien",

        # Maintenance — rules
        "maint.rule_new":        "Nouvelle règle",
        "maint.rule_edit":       "Modifier la règle",
        "maint.rule_name":       "Nom de la règle",
        "maint.service_type":    "Type d'entretien",
        "maint.rule_type":       "Déclencheur",
        "maint.severity":        "Gravité",
        "maint.interval":        "Intervalle",
        "maint.interval_hint":   "km, heures, voyages ou jours selon le type.",
        "maint.advance_warning": "Préavis (avant échéance)",
        "maint.target":          "Cible",
        "maint.rule_active":     "Règle active",
        "maint.days":            "jours",
        "maint.trips_unit":      "voyages",
        "maint.ruletype.km_recurring":    "Récurrent (km)",
        "maint.ruletype.hours_recurring": "Récurrent (heures)",
        "maint.ruletype.trips_recurring": "Récurrent (voyages)",
        "maint.ruletype.time_recurring":  "Récurrent (temps)",
        "maint.sev.info":        "Info",
        "maint.sev.warning":     "Avertissement",
        "maint.sev.critical":    "Critique",
        "maint.target.all":      "Tous les véhicules",
        "maint.target.fleet":    "Flotte",
        "maint.target.category": "Catégorie",
        "maint.target.vehicle":  "Véhicule",
        "maint.rules_empty":     "Aucune règle d'entretien.",
        "maint.rule_created":    "Règle créée.",
        "maint.rule_updated":    "Règle mise à jour.",
        "maint.rule_deleted":    "Règle supprimée.",
        "maint.rule_delete_confirm": "Supprimer cette règle et ses alertes ?",
        # Maintenance — records
        "maint.record_new":      "Nouvel entretien",
        "maint.record_edit":     "Modifier l'entretien",
        "maint.vehicle":         "Véhicule",
        "maint.record_type":     "Type d'entretien",
        "maint.date":            "Date",
        "maint.cost":            "Coût (GNF)",
        "maint.operator":        "Conducteur",
        "maint.supplier":        "Fournisseur",
        "maint.description":     "Description",
        "maint.all_vehicles":    "Tous les véhicules",
        "maint.records_empty":   "Aucun entretien enregistré.",
        "maint.record_created":  "Entretien enregistré.",
        "maint.record_updated":  "Entretien mis à jour.",
        "maint.record_deleted":  "Entretien supprimé.",
        "maint.record_submitted": "Entretien soumis pour validation.",
        "maint.record_delete_confirm": "Supprimer cet entretien ?",
        "maint.rtype.oil_change": "Vidange",
        "maint.rtype.filter":    "Filtres",
        "maint.rtype.tires":     "Pneus",
        "maint.rtype.brakes":    "Freins",
        "maint.rtype.repair":    "Réparation",
        "maint.rtype.parts":     "Pièces détachées",
        "maint.rtype.revision":  "Révision",
        "maint.rtype.other":     "Autre",
        # Alerts
        "maint.alerts.active":   "Actives",
        "maint.alerts.snoozed":  "Reportées",
        "maint.alerts.resolved": "Résolues",
        "maint.alerts.dismissed": "Ignorées",
        "maint.alerts_empty":    "Aucune alerte. Tout est à jour.",
        "maint.log_service":     "Enregistrer l'entretien",
        "maint.snooze":          "Reporter",
        "maint.resolve":         "Résoudre",
        "maint.dismiss":         "Ignorer",
        "maint.snoozed_until":   "reporté au",
        "maint.status.open":     "Ouverte",
        "maint.status.snoozed":  "Reportée",
        "maint.status.resolved": "Résolue",
        "maint.status.dismissed": "Ignorée",
        "maint.alert_snoozed":   "Alerte reportée.",
        "maint.alert_resolved":  "Alerte résolue.",
        "maint.alert_dismissed": "Alerte ignorée.",
        # Maintenance errors
        "maint.err.name_required":     "Le nom est obligatoire.",
        "maint.err.type_required":     "Veuillez choisir un déclencheur.",
        "maint.err.service_type_required": "Veuillez choisir un type d'entretien.",
        "maint.err.interval_required": "Intervalle invalide.",
        "maint.err.bad_number":        "Valeur numérique invalide.",
        "maint.err.target":            "Cible invalide.",
        "maint.err.tracking_mismatch": "Ce type de règle ne correspond pas au mode de suivi de la cible (voyages, heures…).",
        "maint.err.vehicle_required":  "Veuillez choisir un véhicule.",
        "maint.err.rtype_required":    "Veuillez choisir un type d'entretien.",
        "maint.err.date_required":     "Date invalide.",

        # Units & common
        "unit.trips": "voyage",
        "unit.hours": "heure",
        "common.coming_soon": "Bientôt disponible",
        "btn.back": "Retour",
        "btn.view": "Voir",

        # Roles
        "role.super_admin": "Super admin",
        "role.user":        "Utilisateur",

        # Users admin
        "user.new":            "Nouvel utilisateur",
        "user.username":       "Nom d'utilisateur",
        "user.full_name":      "Nom complet",
        "user.email":          "Courriel (facultatif)",
        "user.password":       "Mot de passe",
        "user.new_password":   "Nouveau mot de passe",
        "user.active":         "Actif",
        "user.inactive":       "Inactif",
        "user.access":         "Accès",
        "user.no_access":      "Aucun accès attribué",
        "user.basic_info":     "Informations",
        "user.assignments":    "Accès aux flottes",
        "user.assignments_hint": "Attribuez un rôle par flotte. L'utilisateur ne verra que les véhicules de ses flottes.",
        "user.add_access":     "Attribuer",
        "user.fleet":          "Flotte",
        "user.role":           "Rôle",
        "user.remove":         "Retirer",
        "user.reset_password": "Réinitialiser le mot de passe",
        "user.empty":          "Aucun utilisateur.",
        "user.created":        "Utilisateur créé. Attribuez-lui un accès.",
        "user.updated":        "Utilisateur mis à jour.",
        "user.deleted":        "Utilisateur supprimé.",
        "user.password_reset": "Mot de passe réinitialisé.",
        "user.assigned":       "Accès attribué.",
        "user.unassigned":     "Accès retiré.",
        "user.delete_confirm": "Supprimer cet utilisateur ?",
        "user.err.username_required": "Nom d'utilisateur obligatoire.",
        "user.err.name_required":     "Nom complet obligatoire.",
        "user.err.password_short":    "Mot de passe : 6 caractères minimum.",
        "user.err.username_taken":    "Ce nom d'utilisateur existe déjà.",
        "user.err.email_taken":       "Ce courriel est déjà utilisé.",
        "user.err.assign":            "Choisissez une flotte et un rôle.",

        # Approvals
        "approval.pending":      "En attente",
        "approval.approved_tab": "Approuvées",
        "approval.rejected_tab": "Refusées",
        "approval.empty":        "Aucune validation en attente. Tout est à jour.",
        "approval.reason":       "Motif",
        "myreq.intro":           "Suivez ici l'état de vos demandes soumises à validation.",
        "myreq.in_progress":     "En cours de traitement",
        "myreq.empty":           "Aucune demande pour l'instant.",
        "pending.create":        "Création en attente",
        "pending.update":        "Modification en attente",
        "pending.delete":        "Suppression en attente",
        "approval.note":         "Note (facultatif)",
        "approval.approve":      "Approuver",
        "approval.reject":       "Refuser",
        "approval.reject_confirm": "Refuser cette demande ?",
        "approval.already":      "Cette demande a déjà été traitée.",
        "approval.apply_failed": "Impossible d'appliquer : ressource introuvable.",
        "approval.approved":     "Demande approuvée et appliquée.",
        "approval.rejected":     "Demande refusée.",
        "approval.status.approved": "Approuvée",
        "approval.status.rejected": "Refusée",
        "approval.action.create": "Créer",
        "approval.action.update": "Modifier",
        "approval.action.delete": "Supprimer",
        "approval.res.vehicle":            "Véhicule",
        "approval.res.operator":           "Conducteur",
        "approval.res.daily_entry":        "Saisie quotidienne",
        "approval.res.expense":            "Dépense",
        "approval.res.maintenance_record": "Entretien",

        # Export (saisie quotidienne)
        "export.print_btn":    "Imprimer",
        "export.print_hint":   "Aperçu avant impression — utilisez « Enregistrer au format PDF » dans la fenêtre d'impression pour obtenir un fichier.",
        "export.truncated":    "Document limité aux 1000 lignes les plus récentes — affinez les filtres.",
        "export.title":        "Saisie quotidienne",
        "export.all_vehicles": "Tous les véhicules",
        "export.recent":       "Saisies récentes",
        "export.generated":    "Généré le",
        "export.count":        "saisies",
        "export.voyages":      "Total voyages",
        "export.heures":       "Total heures",
        "export.km":           "Total km",
        "export.responsible":  "Responsable du site",
        "export.validated":    "Validé par",
        "export.name_date":    "Nom / Date",
        "export.confidential": "Document interne — confidentiel",

        # Roles admin
        "role.new":            "Nouveau rôle",
        "role.edit":           "Modifier le rôle",
        "role.name":           "Nom du rôle",
        "role.description":    "Description",
        "role.permissions":    "Permissions",
        "role.can_approve":    "Validation",
        "role.can_approve_full": "Peut valider les changements en attente de ses flottes",
        "role.approver":       "Validateur",
        "role.system":         "Système",
        "role.empty":          "Aucun rôle.",
        "role.created":        "Rôle créé.",
        "role.updated":        "Rôle mis à jour.",
        "role.deleted":        "Rôle supprimé.",
        "role.delete_confirm": "Supprimer définitivement ce rôle ? Cette action est irréversible. Pour un retrait réversible, utilisez plutôt Archiver.",
        "role.holders":        "Utilisateurs",
        "role.delete_system_confirm": "Supprimer ce rôle système ? Il ne sera pas recréé au prochain déploiement. Irréversible depuis l'application (un administrateur technique peut le restaurer).",
        "role.delete_blocked": "Attribué",
        "role.grid_hint":      "Pour chaque action : Interdit (aucun accès), Direct (appliqué immédiatement) ou Validation (mis en file d'attente).",
        "role.set_all":        "Tout :",
        "role.legend.cannot":  "aucun accès",
        "role.legend.direct":  "appliqué immédiatement",
        "role.legend.approval": "mis en file de validation",
        "role.err.name_required": "Le nom est obligatoire.",
        "role.err.name_taken":    "Un rôle porte déjà ce nom.",
        "role.err.system":        "Les rôles système ne peuvent pas être supprimés.",
        "role.err.in_use":        "Ce rôle est attribué à des utilisateurs.",
        "role.err.own_role":      "Vous ne pouvez pas modifier votre propre rôle. Demandez au super administrateur.",
        "role.your_role":         "Votre rôle",
        "role.admin_note":        "Donne accès aux écrans de configuration correspondants. Un rôle ne peut jamais accorder plus de droits que ceux de la personne qui le modifie.",
        "perm.res.dashboard":          "Tableau de bord",
        "perm.res.vehicle":            "Véhicules",
        "perm.res.operator":           "Conducteurs",
        "perm.res.entry":              "Saisies quotidiennes",
        "perm.res.maintenance_record": "Entretiens",
        "perm.res.maintenance_rule":   "Règles d'entretien",
        "perm.res.alert":              "Alertes",
        "perm.res.expense":            "Dépenses",
        "perm.res.insights":           "Analyse",
        "perm.res.invoicing":          "Facturation",
        "perm.res.report":             "Rapports",
        "perm.res.carburant":          "Carburant",
        "perm.res.admin":              "Administration",
        "perm.action.view":    "Voir",
        "perm.action.create":  "Créer",
        "perm.action.edit":    "Modifier",
        "perm.action.delete":  "Supprimer",
        "perm.action.export":  "Imprimer / exporter",
        "perm.action.resolve": "Résoudre",
        "perm.action.dismiss": "Ignorer",
        "perm.action.fleets":     "Gérer les flottes",
        "perm.action.roles":      "Gérer les rôles",
        "perm.action.categories": "Gérer les catégories",
        "perm.action.manage":     "Gérer",
        "perm.state.cannot":   "Interdit",
        "perm.state.direct":   "Direct",
        "perm.state.approval": "Validation",

        # Errors
        "error.forbidden":  "Accès refusé",
        "error.not_found":  "Page introuvable",

        # Common buttons / labels
        "btn.save":   "Enregistrer",
        "btn.cancel": "Annuler",
        "btn.edit":   "Modifier",
        "btn.delete": "Supprimer",
        "btn.archive":    "Archiver",
        "btn.reactivate": "Réactiver",
        "btn.new":    "Nouveau",
        "archive.title":          "Archiver ?",
        "archive.confirm":        "Cet élément sera masqué mais son historique est conservé, et vous pourrez le réactiver.",
        "archive.show_archived":  "Afficher les archivés",
        "archive.show_active":    "← Voir les actifs",
        "archive.empty":          "Aucun élément archivé.",
        "confirm.delete_title":   "Supprimer ?",
        "btn.approve": "Approuver",
        "btn.reject":  "Refuser",
        "btn.dismiss": "Ignorer",
        "btn.submit_for_approval": "Soumettre pour validation",

        # Forms
        "form.optional": "Facultatif",
        "form.required": "Obligatoire",
        "form.select":   "Sélectionner…",
        "form.search":   "Rechercher…",

        # Vehicle categories admin
        "vcat.new":            "Nouvelle catégorie",
        "vcat.edit":           "Modifier la catégorie",
        "vcat.code":           "Code",
        "vcat.code_hint":      "Identifiant interne, en majuscules (ex. BUS). Non modifiable ensuite.",
        "vcat.label":          "Libellé (EN)",
        "vcat.label_fr":       "Libellé (FR)",
        "vcat.unit_type":      "Unité de suivi",
        "vcat.unit.trips":     "Voyages",
        "vcat.unit.hours":     "Heures",
        "vcat.tracking":       "Méthode de suivi",
        "vcat.tracking_hint":  "Comment la saisie quotidienne est enregistrée pour ce type.",
        "vcat.track.trips":        "Voyages (compteur de rotations)",
        "vcat.track.hours":        "Heures (saisie directe)",
        "vcat.track.hours_index":  "Heures (index horomètre début/fin)",
        "vcat.baseline":       "Consommation (L/unité)",
        "vcat.baseline_hint":  "Consommation de référence par défaut.",
        "vcat.cost":           "Coût par unité (GNF)",
        "vcat.cost_hint":      "Pour la perte d'exploitation.",
        "vcat.sort_order":     "Ordre",
        "vcat.usage":          "Véhicules",
        "vcat.empty":          "Aucune catégorie.",
        "vcat.created":        "Catégorie créée.",
        "vcat.updated":        "Catégorie mise à jour.",
        "vcat.deleted":        "Catégorie supprimée.",
        "vcat.delete_confirm": "Supprimer cette catégorie ?",
        "vcat.err.code_required":  "Le code est obligatoire.",
        "vcat.err.code_taken":     "Ce code existe déjà.",
        "vcat.err.label_required": "Les libellés sont obligatoires.",
        "vcat.err.unit_required":  "Choisissez un type d'unité.",
        "vcat.err.bad_number":     "Valeur numérique invalide.",
        "vcat.err.delete_blocked": "Impossible de supprimer : des véhicules ou flottes utilisent cette catégorie.",

        # Vehicle categories (master list labels for UI)
        "cat.bus":        "Bus",
        "cat.minibus":    "Minibus",
        "cat.navette":    "Navette",
        "cat.camion_tsf": "Camion TSF",
        "cat.machine_tsf": "Machine TSF",
        "cat.citerne":    "Citerne",
        "cat.service":    "Véhicule de service",
        "cat.autre":      "Autre",

        # Permissions categories (for the role grid)
        "perm.cat.vehicles":     "Véhicules",
        "perm.cat.operators":    "Conducteurs",
        "perm.cat.entries":      "Saisies",
        "perm.cat.maintenance":  "Maintenance",
        "perm.cat.expenses":     "Dépenses",
        "perm.cat.reports":      "Rapports",
        "perm.cat.alerts":       "Alertes",
        "perm.cat.admin":        "Administration",

        # Photo errors (carried over from batmex)
        "photo.upload_required":             "Une photo du bon est obligatoire.",
        "photo.upload_required_with_reason": "La photo n'a pas pu être enregistrée, donc la saisie n'a pas été sauvegardée.",
        "photo.err.not_configured":          "Le stockage des photos n'est pas configuré sur le serveur — contacte l'admin.",
        "photo.err.too_large":               "Photo trop volumineuse (plus de 12 Mo). Reprends une photo ou choisis-en une plus petite.",
        "photo.err.bad_format":              "Format de photo non supporté (souvent un HEIC iPhone). Utilise l'appareil photo en JPEG, ou choisis une JPEG/PNG depuis la galerie.",
        "photo.err.s3_error":                "Impossible de joindre le stockage photo — problème de connexion. Réessaie quand le réseau est meilleur.",
        "photo.err.unknown":                 "Échec de l'envoi de la photo — erreur inconnue. Réessaie ; si ça persiste, contacte l'admin.",

        # ── Placeholders: worked examples shown inside empty inputs ──
        "ph.vehicle.code":        "ex. BUS-001",
        "ph.vehicle.site":        "ex. Kamsar",
        "ph.vehicle.baseline":    "ex. 12,5",
        "ph.vehicle.description": "ex. Bus 45 places affecté au transport du personnel",
        "ph.operator.name":       "ex. Mamadou Diallo",
        "ph.operator.phone":      "ex. 622 00 00 00",
        "ph.operator.license":    "ex. GN-2021-004512",
        "ph.operator.notes":      "ex. Habilité conduite bus et camion",
        "ph.fleet.name":          "ex. Zone Nord",
        "ph.fleet.slug":          "ex. zone-nord (généré automatiquement si vide)",
        "ph.fleet.description":   "ex. Flotte du site de Kamsar",
        "ph.expense.amount":      "ex. 250000",
        "ph.expense.liters":      "ex. 45",
        "ph.expense.supplier":    "ex. Total Kamsar",
        "ph.expense.description": "ex. Plein gasoil avant mission",
        "ph.record.cost":         "ex. 1500000",
        "ph.record.supplier":     "ex. Garage Central",
        "ph.record.description":  "ex. Vidange moteur + remplacement filtres",
        "ph.rule.name":           "ex. Vidange moteur",
        "ph.rule.interval":       "ex. 5000",
        "ph.rule.warning":        "ex. 500",
        "ph.vcat.code":           "ex. BUS",
        "ph.vcat.label":          "ex. Bus",
        "ph.vcat.baseline":       "ex. 12,5",
        "ph.vcat.sort":           "ex. 1",
        "ph.role.name":           "ex. Chef de parc",
        "ph.role.description":    "ex. Peut saisir et valider les pointages du site",
        "ph.user.username":       "ex. mdiallo",
        "ph.user.full_name":      "ex. Mamadou Diallo",
        "ph.user.email":          "ex. mdiallo@zone-equip.com",
        "ph.entry.trips":         "ex. 3",
        "ph.entry.hours":         "ex. 7,5",
        "ph.entry.index":         "ex. 1245,5",
        "ph.entry.km":            "ex. 120",
        "ph.entry.note":          "ex. Retard au chargement",
    },

    # ── English ───────────────────────────────────────────────────────────
    "en": {
        "app.title": "Zone Web",
        "app.tagline": "Fleet tracking",

        "auth.login":             "Login",
        "auth.logout":            "Log out",
        "auth.username":          "Username",
        "auth.email":             "Email",
        "auth.email_optional":    "Email (optional)",
        "auth.password":          "Password",
        "auth.sign_in":           "Sign in",
        "auth.invalid_credentials": "Invalid credentials.",
        "auth.required":          "Please log in.",

        "dash.welcome":   "Welcome",
        "dash.super_sub": "Super admin — full access to configuration and all fleets.",
        "dash.month_spend":      "This month's spend",
        "dash.pending":          "To approve",
        "dash.open_alerts":      "Open alerts",
        "dash.recent_activity":  "Recent activity",
        "dash.no_alerts":        "No open alerts. All clear.",
        "dash.no_activity":      "No recent entries.",
        "dash.view_all":         "View all",
        "dash.spend_trend":      "Spend trend",
        "dash.last_6_months":    "Last 6 months",
        "dash.spend_by_cat":     "Spend by category",
        # Operational dashboard
        "dash.month_hours":      "Hours worked (month)",
        "dash.month_trips":      "Trips (month)",
        "dash.month_km":         "Kilometers (month)",
        "dash.month_liters":     "Fuel (month)",
        "dash.active_vehicles":  "Vehicles active this month",
        "dash.activity_trend":   "Monthly activity",
        "dash.top_vehicles":     "Busiest vehicles",
        "dash.daily_entries":    "Entries per day",
        "dash.fuel_trend":       "Fuel consumption",
        "dash.entries":          "Entries",
        "dash.this_month":       "This month",
        "dash.last_30_days":     "Last 30 days",

        # First-login welcome guide
        "tour.title":   "Getting started",
        "tour.hello":   "Welcome",
        "tour.intro":   "Here are the steps to get the most out of the platform, in order.",
        "tour.go":      "Open",
        "tour.start":   "Get started",
        "tour.close":   "Close the guide",
        "tour.replay":  "Replay the guide",
        "tour.replay_hint": "You can replay it any time.",
        "tour.fleets.t":    "Create your fleets (clients)",
        "tour.fleets.d":    "One fleet per client; tick its machine types and set the rates.",
        "tour.operators.t": "Add the drivers",
        "tour.operators.d": "The drivers of each fleet.",
        "tour.vehicles.t":  "Add the vehicles",
        "tour.vehicles.d":  "Category, fleet and default driver.",
        "tour.users.t":     "Create the users",
        "tour.users.d":     "Staff and their per-fleet access.",
        "tour.rules.t":     "Set maintenance rules",
        "tour.rules.d":     "Thresholds in km, hours or days.",
        "tour.entry.t":     "Log daily activity",
        "tour.entry.d":     "Each day: activity, km and driver per vehicle.",
        "tour.carburant.t": "Track fuel",
        "tour.carburant.d": "Create your citernes, then log what each machine draws from them.",
        "tour.expense.t":   "Record expenses",
        "tour.expense.d":   "Fuel and other costs.",
        "tour.maint.t":     "Log maintenance",
        "tour.maint.d":     "Logging a service resolves its alert.",
        "tour.alerts.t":    "Watch alerts",
        "tour.alerts.d":    "Upcoming or overdue maintenance.",
        "tour.dashboard.t": "Check the dashboard",
        "tour.dashboard.d": "The at-a-glance overview.",
        "tour.insights.t":  "Analyse",
        "tour.insights.d":  "Fuel vs baseline, costs, idle vehicles.",
        "tour.invoicing.t": "Bill clients",
        "tour.invoicing.d": "Worked units × rate, per month.",

        "nav.dashboard":            "Dashboard",
        "nav.vehicles":             "Vehicles",
        "nav.operators":            "Operators",
        "nav.roster":               "Roster",
        "nav.daily_entries":        "Daily entries",
        "nav.maintenance":          "Maintenance",
        "nav.maintenance_records":  "Maintenance history",
        "nav.maintenance_rules":    "Maintenance rules",
        "nav.alerts":               "Alerts",
        "nav.expenses":             "Expenses",
        "nav.insights":             "Insights",
        "nav.invoicing":            "Invoicing",
        "nav.reports":              "Reports",
        "nav.management":           "Management",
        "nav.validation":           "Validation",
        "nav.approvals":            "Pending approvals",
        "nav.my_requests":          "My requests",
        "nav.help":                 "Help",
        "help.toc":                 "Contents",
        "help.note":                "Note",
        "help.print":               "Print",
        "nav.admin":                "Administration",
        "nav.change_password":      "Change password",

        # Operations insights
        "insights.fleet_total":   "Total fleet cost",
        "insights.over_baseline": "Over-baseline (fuel)",
        "insights.idle_count":    "Idle vehicles",
        "insights.fuel_title":    "Fuel: actual vs. baseline",
        "insights.fuel_hint":     "Actual consumption compared to baseline (activity × expected liters).",
        "insights.fuel_empty":    "Not enough data: needs a consumption baseline, activity and fuel fill-ups in the period.",
        "insights.activity":      "Activity",
        "insights.expected_l":    "Expected",
        "insights.actual_l":      "Actual",
        "insights.variance":      "Variance",
        "insights.cost_title":    "Cost per vehicle",
        "insights.other":         "Other",
        "insights.total":         "Total",
        "insights.per_unit":      "Cost/unit",
        "insights.per_km":        "Cost/km",
        "insights.cost_note":     "Cost = fuel + maintenance + other expenses, over the period.",
        "insights.idle_title":    "Idle / under-utilised vehicles",
        "insights.idle_hint":     "Flagged after %d days with no entry.",
        "insights.last_activity": "Last activity",
        "insights.days_idle":     "Days idle",
        "insights.idle_badge":    "Idle",
        "insights.never":         "Never",
        "insights.idle_empty":    "No active vehicles.",

        # Password change
        "pw.title":                  "Change password",
        "pw.error.wrong_current":    "Current password is incorrect.",
        "pw.error.too_short":        "New password must be at least 6 characters.",
        "pw.error.no_match":         "The two new passwords do not match.",
        "pw.success":                "Password updated.",
        "form.current_password":     "Current password",
        "form.new_password":         "New password",
        "form.confirm_password":     "Confirm new password",
        "form.update_password":      "Update password",

        "admin.users":      "Users",
        "admin.fleets":     "Fleets",
        "admin.roles":      "Roles",
        "admin.categories": "Vehicle categories",
        "admin.settings":   "Settings",
        "admin.audit_log":  "Activity log",

        # Activity log viewer
        "audit.entries":       "entries",
        "audit.timestamp":     "Timestamp",
        "audit.user":          "User",
        "audit.action":        "Action",
        "audit.resource":      "Resource",
        "audit.detail":        "Detail",
        "audit.ip":            "IP",
        "audit.search_user":   "Search a user",
        "audit.all_actions":   "All actions",
        "audit.all_resources": "All resources",
        "audit.all_fleets":    "All fleets",
        "audit.empty":         "No entries in the log.",
        "audit.prev":          "Previous",
        "audit.next":          "Next",
        "audit.page":          "Page",

        # Settings
        "setting.cat.approval":      "Approval",
        "setting.cat.general":       "General",
        "setting.grace_period_minutes": "Grace period for self-corrections (minutes)",
        "setting.currency":          "Default currency",
        "setting.default_lang":      "Default language",
        "setting.lang.fr":           "French",
        "setting.lang.en":           "English",
        "setting.updated":           "Updated",
        "setting.saved":             "Settings saved.",
        "setting.err.number":        "Invalid numeric value.",
        "setting.err.range":         "Value out of range.",
        "setting.err.choice":        "Invalid choice.",

        # Fleets
        "fleet.new":            "New fleet",
        "fleet.edit":           "Edit fleet",
        "fleet.name":           "Name",
        "fleet.name_hint":      "e.g. Staff transport",
        "fleet.slug":           "Slug",
        "fleet.slug_hint":      "auto-generated if left blank",
        "fleet.description":    "Description",
        "fleet.categories":     "Vehicle categories",
        "fleet.rates_hint":     "Tick this client's machine types and set the rate billed per worked unit.",
        "fleet.categories_hint": "Tick the machine types this client operates.",
        "fleet.rate_ph":        "Rate",
        "fleet.rate_effective_from": "Rates effective from",
        "fleet.rate_effective_hint": "Changing a rate creates a new dated value (history is kept).",
        "fleet.err.bad_rate":   "Invalid rate.",
        "fleet.vehicles":       "Vehicles",
        "fleet.users":          "Users",

        # Invoicing / facturation
        "invoicing.client":       "Client",
        "invoicing.units":        "Worked units",
        "invoicing.rate":         "Rate",
        "invoicing.amount":       "Amount",
        "invoicing.total_client": "Total to bill",
        "invoicing.no_rate":      "no rate",
        "invoicing.missing_rate_warn": "Some entries have no rate set for their date — that amount is not billed. Set the rate on the fleet page.",
        "invoicing.note":         "Amount = worked units × the rate in force on each entry's date.",
        "invoicing.empty":        "No billable activity for this client this month.",
        "fleet.empty":          "No fleets yet.",
        "fleet.created":        "Fleet created.",
        "fleet.updated":        "Fleet updated.",
        "fleet.deleted":        "Fleet deleted.",
        "fleet.delete_confirm": "Delete this fleet?",
        "fleet.err.name_required": "Name is required.",
        "fleet.err.name_taken":    "A fleet with this name already exists.",
        "fleet.err.slug_taken":    "That slug is already in use.",
        "fleet.err.delete_blocked": "Cannot delete: vehicles, operators or users are still attached to this fleet.",

        # Vehicles
        "vehicle.new":            "New vehicle",
        "vehicle.edit":           "Edit vehicle",
        "vehicle.all":            "All",
        "vehicle.code":           "Code / Plate",
        "vehicle.category":       "Category",
        "vehicle.fleet":          "Fleet",
        "vehicle.site":           "Site",
        "vehicle.description":    "Description",
        "vehicle.default_operator":      "Default driver",
        "vehicle.default_operator_hint": "Optional — pre-fills the daily entry. Chosen from the fleet's registered drivers.",
        "vehicle.no_default_operator":   "None",
        "vehicle.err.operator_fleet":    "The default driver must belong to the vehicle's fleet.",
        "vehicle.baseline":       "Baseline consumption",
        "vehicle.baseline_override": "Consumption (L/unit)",
        "vehicle.baseline_hint":  "Leave blank to use the category default.",
        "vehicle.cost_override":  "Cost per unit (GNF)",
        "vehicle.cost_hint":      "Leave blank to use the category default.",
        "vehicle.active":         "Active",
        "vehicle.inactive":       "Inactive",
        "vehicle.is_active":      "Vehicle active",
        "vehicle.status":         "Status",
        "vehicle.from_category":  "category default",
        "vehicle.empty":          "No vehicles yet.",
        "vehicle.created":        "Vehicle created.",
        "vehicle.updated":        "Vehicle updated.",
        "vehicle.deleted":        "Vehicle deleted.",
        "vehicle.submitted":      "Change submitted for approval.",
        "vehicle.delete_confirm": "Delete this vehicle?",
        "vehicle.err.code_required":     "Vehicle code is required.",
        "vehicle.err.fleet_required":    "Please choose a fleet.",
        "vehicle.err.category_required": "Please choose a category.",
        "vehicle.err.code_taken":        "A vehicle with this code already exists.",
        "vehicle.err.cat_not_in_fleet":  "That category does not belong to the chosen fleet.",
        "vehicle.err.bad_number":        "Invalid numeric value.",
        "vehicle.err.delete_blocked":    "Cannot delete: entries, maintenance or expenses are attached to this vehicle.",

        # Operators (drivers)
        "operator.new":            "New operator",
        "operator.edit":           "Edit operator",
        "operator.all":            "All",
        "operator.name":           "Name",
        "operator.fleet":          "Fleet",
        "operator.phone":          "Phone",
        "operator.license":        "Licence no.",
        "operator.notes":          "Notes",
        "operator.active":         "Active",
        "operator.inactive":       "Inactive",
        "operator.is_active":      "Operator active",
        "operator.status":         "Status",
        "operator.last_activity":  "Last log",
        "operator.activity":       "Activity",
        "operator.kpi.pointages":  "Logs",
        "operator.kpi.hours":      "Hours",
        "operator.kpi.trips":      "Trips",
        "operator.kpi.km":         "Kilometers",
        "operator.expenses":       "Expenses",
        "operator.expenses_hint":  "Expenses and services attributed to this driver, by month and category.",
        "operator.exp_maintenance": "Maintenance",
        "operator.no_expenses":    "No expenses in this period.",
        "operator.vehicles":       "Vehicles driven",
        "operator.default_badge":  "Default",
        "operator.no_vehicles":    "No vehicle linked.",
        "operator.records":        "Linked services",
        "operator.no_records":     "No linked service.",
        "operator.empty":          "No operators yet.",
        "operator.created":        "Operator created.",
        "operator.updated":        "Operator updated.",
        "operator.deleted":        "Operator deleted.",
        "operator.submitted":      "Change submitted for approval.",
        "operator.delete_confirm": "Delete this operator?",
        "operator.err.name_required":  "Name is required.",
        "operator.err.fleet_required": "Please choose a fleet.",
        "operator.err.name_taken":     "An operator with this name already exists in this fleet.",

        # Daily entries
        "entry.new":            "New entry",
        "entry.edit":           "Edit entry",
        "entry.add":            "Add",
        "entry.vehicle":        "Vehicle",
        "entry.date":           "Date",
        "entry.trips":          "Trips",
        "entry.hours":          "Hours",
        "entry.index_start":    "Index start",
        "entry.index_end":      "Index end",
        "entry.hours_auto":     "Hours (auto)",
        "entry.err.index_order": "End index must be greater than or equal to the start index.",
        "entry.fuel":           "Fuel (L)",
        "entry.km":             "Kilometers",
        "entry.operator":       "Driver",
        "entry.note":           "Note",
        "entry.activity":       "Activity",
        "entry.all_vehicles":   "All vehicles",
        "entry.all_fleets":     "All fleets",
        "entry.all_operators":  "All drivers",
        "entry.all_categories": "All categories",
        "entry.month":          "Month",
        "entry.or":             "or",
        "entry.filter":         "Filter",
        "entry.more_filters":   "More filters",
        "entry.from":           "From",
        "entry.to":             "To",
        "entry.clear":          "Clear",
        "entry.empty":          "No entries yet.",
        "entry.created":        "Entry saved.",
        "entry.updated":        "Entry updated.",
        "entry.deleted":        "Entry deleted.",
        "entry.submitted":      "Entry submitted for approval.",
        "entry.err.pending_exists": "A request is already pending for this entry; it must be processed first.",
        "entry.delete_confirm": "Delete this entry?",
        "entry.err.vehicle_required": "Please choose a vehicle.",
        "entry.err.date_required":    "Invalid date.",
        "entry.err.bad_number":       "Invalid numeric value.",
        "entry.err.negative":         "Values cannot be negative.",

        # Roster
        "roster.prev_day":   "Previous day",
        "roster.next_day":   "Next day",
        "roster.done":       "done",
        "roster.pending":    "pending",
        "roster.tap_to_log": "Tap to log",
        "roster.no_vehicles": "No active vehicles in this fleet.",
        "roster.no_fleet":   "No accessible fleet. Ask for fleet access.",

        # Expenses
        "expense.new":            "New expense",
        "expense.edit":           "Edit expense",
        "expense.add":            "Add",
        "expense.all":            "All",
        "expense.category":       "Category",
        "expense.date":           "Date",
        "expense.fleet":          "Fleet",
        "expense.vehicle":        "Vehicle",
        "expense.fleet_wide":     "Fleet-wide",
        "expense.target":         "Vehicle / Fleet",
        "expense.amount":         "Amount (GNF)",
        "expense.liters":         "Litres",
        "expense.operator":       "Driver (optional)",
        "expense.supplier":       "Supplier",
        "expense.description":    "Description",
        "expense.total":          "Total: ",
        "expense.count":          "expenses",
        "expense.empty":          "No expenses yet.",
        "expense.created":        "Expense saved.",
        "expense.updated":        "Expense updated.",
        "expense.deleted":        "Expense deleted.",
        "expense.submitted":      "Expense submitted for approval.",
        "expense.delete_confirm": "Delete this expense?",
        "expense.err.category_required": "Please choose a category.",
        "expense.err.fleet_required":    "Please choose a fleet.",
        "expense.err.vehicle_fleet":     "The vehicle does not belong to the chosen fleet.",
        "expense.err.vehicle_required":  "Please choose a vehicle.",
        "expense.err.label_required":    "Please name the expense.",
        "expense.err.payment_required":  "Please choose a payment method.",
        "expense.err.maintenance_locked": "This expense comes from a service: edit it on the service record.",
        "expense.err.date_required":     "Invalid date.",
        "expense.err.amount_required":   "Invalid amount.",
        "expense.err.bad_number":        "Invalid numeric value.",
        # Expenses — vehicle or general
        "expense.is_vehicle":     "This expense concerns a vehicle",
        "expense.label":          "Expense name",
        "expense.company":        "Company expense",
        "expense.filter.general": "General",
        "expense.from_maint":     "From a service",
        # Payment
        "expense.payment_method":    "Payment method",
        "expense.payment_reference": "Reference (optional)",
        "pay.mobile_money": "Mobile Money",
        "pay.cash":         "Cash",
        "pay.transfer":     "Bank transfer",
        "pay.cheque":       "Cheque",
        "pay.other":        "Other",
        # Fuel
        "nav.fuel":          "Fuel",
        "fuel.new":          "New fill-up",
        "citerne.new":          "New citerne",
        "citerne.edit":         "Edit citerne",
        "citerne.code":         "Code",
        "citerne.name":         "Name",
        "citerne.fleet":        "Fleet",
        "citerne.capacity":     "Capacity (litres)",
        "citerne.stock":        "Current stock",
        "citerne.initial":      "Opening stock (litres)",
        "citerne.initial_hint": "The fuel already in the tanker. Fills at the client come in the next step.",
        "citerne.created":      "Citerne created.",
        "citerne.updated":      "Citerne updated.",
        "citerne.archived":     "Citerne archived.",
        "citerne.reactivated":  "Citerne reactivated.",
        "citerne.empty":        "No citerne yet. Create one to get started.",
        "citerne.err.code":         "Code is required.",
        "citerne.err.name":         "Name is required.",
        "citerne.err.capacity":     "Capacity must be positive.",
        "citerne.err.fleet":        "Fleet is required.",
        "citerne.err.over_capacity":"Stock exceeds the capacity.",
        "citerne.err.code_taken":   "This code is already in use.",
        "distribution.new":         "Fuel draw",
        "distribution.recent":      "Recent draws",
        "distribution.date":        "Date",
        "distribution.machine":     "Machine",
        "distribution.citerne":     "Source citerne",
        "distribution.liters":      "Litres taken",
        "distribution.driver":      "Driver",
        "distribution.available":   "available",
        "distribution.created":     "Fuel draw recorded.",
        "distribution.deleted":     "Draw deleted.",
        "distribution.delete_confirm": "Delete this draw? The citerne stock will be credited back.",
        "distribution.err.date":        "Invalid date.",
        "distribution.err.citerne":     "Choose an active citerne.",
        "distribution.err.vehicle":     "Choose a machine.",
        "distribution.err.fleet_mismatch": "The machine and the citerne must be in the same fleet.",
        "distribution.err.liters":      "Invalid litres.",
        "distribution.err.stock":       "Not enough stock in the citerne.",
        "fuel.empty":        "No fill-up recorded.",
        "fuel.liters":       "Litres",
        "fuel.total_liters": "Total litres",
        "fuel.price_per_l":  "Price / litre",
        "fuel.station":      "Station / Supplier",
        "expense.cat.fuel":       "Fuel",
        "expense.cat.vidange":    "Oil change",
        "expense.cat.filtre":     "Filters",
        "expense.cat.pneus":      "Tyres",
        "expense.cat.reparation": "Repair",
        "expense.cat.piece":      "Spare parts",
        "expense.cat.assurance":  "Insurance",
        "expense.cat.accident":   "Accident",
        "expense.cat.lavage":     "Washing",
        "expense.cat.agent":      "Agent fees",
        "expense.cat.autre":      "Other",
        "expense.cat.entretien":  "Maintenance",

        # Maintenance — rules
        "maint.rule_new":        "New rule",
        "maint.rule_edit":       "Edit rule",
        "maint.rule_name":       "Rule name",
        "maint.service_type":    "Service type",
        "maint.rule_type":       "Trigger",
        "maint.severity":        "Severity",
        "maint.interval":        "Interval",
        "maint.interval_hint":   "km, hours, trips or days depending on the type.",
        "maint.advance_warning": "Advance warning",
        "maint.target":          "Target",
        "maint.rule_active":     "Rule active",
        "maint.days":            "days",
        "maint.trips_unit":      "trips",
        "maint.ruletype.km_recurring":    "Recurring (km)",
        "maint.ruletype.hours_recurring": "Recurring (hours)",
        "maint.ruletype.trips_recurring": "Recurring (trips)",
        "maint.ruletype.time_recurring":  "Recurring (time)",
        "maint.sev.info":        "Info",
        "maint.sev.warning":     "Warning",
        "maint.sev.critical":    "Critical",
        "maint.target.all":      "All vehicles",
        "maint.target.fleet":    "Fleet",
        "maint.target.category": "Category",
        "maint.target.vehicle":  "Vehicle",
        "maint.rules_empty":     "No maintenance rules.",
        "maint.rule_created":    "Rule created.",
        "maint.rule_updated":    "Rule updated.",
        "maint.rule_deleted":    "Rule deleted.",
        "maint.rule_delete_confirm": "Delete this rule and its alerts?",
        # Maintenance — records
        "maint.record_new":      "New service",
        "maint.record_edit":     "Edit service",
        "maint.vehicle":         "Vehicle",
        "maint.record_type":     "Service type",
        "maint.date":            "Date",
        "maint.cost":            "Cost (GNF)",
        "maint.operator":        "Driver",
        "maint.supplier":        "Supplier",
        "maint.description":     "Description",
        "maint.all_vehicles":    "All vehicles",
        "maint.records_empty":   "No service records.",
        "maint.record_created":  "Service recorded.",
        "maint.record_updated":  "Service updated.",
        "maint.record_deleted":  "Service deleted.",
        "maint.record_submitted": "Service submitted for approval.",
        "maint.record_delete_confirm": "Delete this service record?",
        "maint.rtype.oil_change": "Oil change",
        "maint.rtype.filter":    "Filters",
        "maint.rtype.tires":     "Tyres",
        "maint.rtype.brakes":    "Brakes",
        "maint.rtype.repair":    "Repair",
        "maint.rtype.parts":     "Spare parts",
        "maint.rtype.revision":  "Service",
        "maint.rtype.other":     "Other",
        # Alerts
        "maint.alerts.active":   "Active",
        "maint.alerts.snoozed":  "Snoozed",
        "maint.alerts.resolved": "Resolved",
        "maint.alerts.dismissed": "Dismissed",
        "maint.alerts_empty":    "No alerts. All up to date.",
        "maint.log_service":     "Log service",
        "maint.snooze":          "Snooze",
        "maint.resolve":         "Resolve",
        "maint.dismiss":         "Dismiss",
        "maint.snoozed_until":   "snoozed until",
        "maint.status.open":     "Open",
        "maint.status.snoozed":  "Snoozed",
        "maint.status.resolved": "Resolved",
        "maint.status.dismissed": "Dismissed",
        "maint.alert_snoozed":   "Alert snoozed.",
        "maint.alert_resolved":  "Alert resolved.",
        "maint.alert_dismissed": "Alert dismissed.",
        # Maintenance errors
        "maint.err.name_required":     "Name is required.",
        "maint.err.type_required":     "Please choose a trigger.",
        "maint.err.service_type_required": "Please choose a service type.",
        "maint.err.interval_required": "Invalid interval.",
        "maint.err.bad_number":        "Invalid numeric value.",
        "maint.err.target":            "Invalid target.",
        "maint.err.tracking_mismatch": "This rule type doesn't match the target's tracking mode (trips, hours…).",
        "maint.err.vehicle_required":  "Please choose a vehicle.",
        "maint.err.rtype_required":    "Please choose a service type.",
        "maint.err.date_required":     "Invalid date.",

        # Units & common
        "unit.trips": "trip",
        "unit.hours": "hour",
        "common.coming_soon": "Coming soon",
        "btn.back": "Back",
        "btn.view": "View",

        "role.super_admin": "Super admin",
        "role.user":        "User",

        # Users admin
        "user.new":            "New user",
        "user.username":       "Username",
        "user.full_name":      "Full name",
        "user.email":          "Email (optional)",
        "user.password":       "Password",
        "user.new_password":   "New password",
        "user.active":         "Active",
        "user.inactive":       "Inactive",
        "user.access":         "Access",
        "user.no_access":      "No access assigned",
        "user.basic_info":     "Details",
        "user.assignments":    "Fleet access",
        "user.assignments_hint": "Assign one role per fleet. The user only sees vehicles in their fleets.",
        "user.add_access":     "Assign",
        "user.fleet":          "Fleet",
        "user.role":           "Role",
        "user.remove":         "Remove",
        "user.reset_password": "Reset password",
        "user.empty":          "No users.",
        "user.created":        "User created. Assign them access.",
        "user.updated":        "User updated.",
        "user.deleted":        "User deleted.",
        "user.password_reset": "Password reset.",
        "user.assigned":       "Access assigned.",
        "user.unassigned":     "Access removed.",
        "user.delete_confirm": "Delete this user?",
        "user.err.username_required": "Username is required.",
        "user.err.name_required":     "Full name is required.",
        "user.err.password_short":    "Password must be at least 6 characters.",
        "user.err.username_taken":    "That username already exists.",
        "user.err.email_taken":       "That email is already in use.",
        "user.err.assign":            "Choose a fleet and a role.",

        # Approvals
        "approval.pending":      "Pending",
        "approval.approved_tab": "Approved",
        "approval.rejected_tab": "Rejected",
        "approval.empty":        "No pending approvals. All caught up.",
        "approval.reason":       "Reason",
        "myreq.intro":           "Track the status of the changes you submitted for approval.",
        "myreq.in_progress":     "Being processed",
        "myreq.empty":           "No requests yet.",
        "pending.create":        "Creation pending",
        "pending.update":        "Update pending",
        "pending.delete":        "Deletion pending",
        "approval.note":         "Note (optional)",
        "approval.approve":      "Approve",
        "approval.reject":       "Reject",
        "approval.reject_confirm": "Reject this request?",
        "approval.already":      "This request was already reviewed.",
        "approval.apply_failed": "Cannot apply: resource not found.",
        "approval.approved":     "Request approved and applied.",
        "approval.rejected":     "Request rejected.",
        "approval.status.approved": "Approved",
        "approval.status.rejected": "Rejected",
        "approval.action.create": "Create",
        "approval.action.update": "Update",
        "approval.action.delete": "Delete",
        "approval.res.vehicle":            "Vehicle",
        "approval.res.operator":           "Operator",
        "approval.res.daily_entry":        "Daily entry",
        "approval.res.expense":            "Expense",
        "approval.res.maintenance_record": "Service record",

        # Export (daily entries)
        "export.print_btn":    "Print",
        "export.print_hint":   "Print preview — use “Save as PDF” in the print dialog to get a file.",
        "export.truncated":    "Limited to the 1000 most recent rows — narrow the filters.",
        "export.title":        "Daily entries",
        "export.all_vehicles": "All vehicles",
        "export.recent":       "Recent entries",
        "export.generated":    "Generated",
        "export.count":        "entries",
        "export.voyages":      "Total trips",
        "export.heures":       "Total hours",
        "export.km":           "Total km",
        "export.responsible":  "Site manager",
        "export.validated":    "Approved by",
        "export.name_date":    "Name / Date",
        "export.confidential": "Internal document — confidential",

        # Roles admin
        "role.new":            "New role",
        "role.edit":           "Edit role",
        "role.name":           "Role name",
        "role.description":    "Description",
        "role.permissions":    "Permissions",
        "role.can_approve":    "Approval",
        "role.can_approve_full": "Can approve pending changes for their fleets",
        "role.approver":       "Approver",
        "role.system":         "System",
        "role.empty":          "No roles.",
        "role.created":        "Role created.",
        "role.updated":        "Role updated.",
        "role.deleted":        "Role deleted.",
        "role.delete_confirm": "Delete this role for good? This cannot be undone. For a reversible removal, archive it instead.",
        "role.holders":        "Users",
        "role.delete_system_confirm": "Delete this system role? It will not be re-created on the next deploy. Irreversible from the app (a technical admin can restore it).",
        "role.delete_blocked": "Assigned",
        "role.grid_hint":      "For each action: Cannot (no access), Direct (applied immediately) or Approval (queued for review).",
        "role.set_all":        "Set all:",
        "role.legend.cannot":  "no access",
        "role.legend.direct":  "applied immediately",
        "role.legend.approval": "queued for approval",
        "role.err.name_required": "Name is required.",
        "role.err.name_taken":    "A role with this name already exists.",
        "role.err.system":        "System roles cannot be deleted.",
        "role.err.in_use":        "This role is assigned to users.",
        "role.err.own_role":      "You cannot edit your own role. Ask the super admin.",
        "role.your_role":         "Your role",
        "role.admin_note":        "Grants access to the matching configuration screens. A role can never be given more power than the person editing it holds.",
        "perm.res.dashboard":          "Dashboard",
        "perm.res.vehicle":            "Vehicles",
        "perm.res.operator":           "Operators",
        "perm.res.entry":              "Daily entries",
        "perm.res.maintenance_record": "Service records",
        "perm.res.maintenance_rule":   "Maintenance rules",
        "perm.res.alert":              "Alerts",
        "perm.res.expense":            "Expenses",
        "perm.res.insights":           "Analytics",
        "perm.res.invoicing":          "Invoicing",
        "perm.res.report":             "Reports",
        "perm.res.carburant":          "Fuel",
        "perm.res.admin":              "Administration",
        "perm.action.view":    "View",
        "perm.action.create":  "Create",
        "perm.action.edit":    "Edit",
        "perm.action.delete":  "Delete",
        "perm.action.export":  "Print / export",
        "perm.action.resolve": "Resolve",
        "perm.action.dismiss": "Dismiss",
        "perm.action.fleets":     "Manage fleets",
        "perm.action.roles":      "Manage roles",
        "perm.action.categories": "Manage categories",
        "perm.action.manage":     "Manage",
        "perm.state.cannot":   "Cannot",
        "perm.state.direct":   "Direct",
        "perm.state.approval": "Approval",

        "error.forbidden":  "Forbidden",
        "error.not_found":  "Not found",

        "btn.save":   "Save",
        "btn.cancel": "Cancel",
        "btn.edit":   "Edit",
        "btn.delete": "Delete",
        "btn.archive":    "Archive",
        "btn.reactivate": "Reactivate",
        "btn.new":    "New",
        "archive.title":          "Archive?",
        "archive.confirm":        "This item will be hidden but its history is kept, and you can reactivate it.",
        "archive.show_archived":  "Show archived",
        "archive.show_active":    "← Back to active",
        "archive.empty":          "No archived items.",
        "confirm.delete_title":   "Delete?",
        "btn.approve": "Approve",
        "btn.reject":  "Reject",
        "btn.dismiss": "Dismiss",
        "btn.submit_for_approval": "Submit for approval",

        "form.optional": "Optional",
        "form.required": "Required",
        "form.select":   "Select…",
        "form.search":   "Search…",

        # Vehicle categories admin
        "vcat.new":            "New category",
        "vcat.edit":           "Edit category",
        "vcat.code":           "Code",
        "vcat.code_hint":      "Internal id, uppercase (e.g. BUS). Not editable afterwards.",
        "vcat.label":          "Label (EN)",
        "vcat.label_fr":       "Label (FR)",
        "vcat.unit_type":      "Tracking unit",
        "vcat.unit.trips":     "Trips",
        "vcat.unit.hours":     "Hours",
        "vcat.tracking":       "Tracking method",
        "vcat.tracking_hint":  "How a daily entry is logged for this type.",
        "vcat.track.trips":        "Trips (rotation count)",
        "vcat.track.hours":        "Hours (direct entry)",
        "vcat.track.hours_index":  "Hours (hour-meter index start/end)",
        "vcat.baseline":       "Consumption (L/unit)",
        "vcat.baseline_hint":  "Default baseline consumption.",
        "vcat.cost":           "Cost per unit (GNF)",
        "vcat.cost_hint":      "For operating-loss calc.",
        "vcat.sort_order":     "Order",
        "vcat.usage":          "Vehicles",
        "vcat.empty":          "No categories.",
        "vcat.created":        "Category created.",
        "vcat.updated":        "Category updated.",
        "vcat.deleted":        "Category deleted.",
        "vcat.delete_confirm": "Delete this category?",
        "vcat.err.code_required":  "Code is required.",
        "vcat.err.code_taken":     "That code already exists.",
        "vcat.err.label_required": "Labels are required.",
        "vcat.err.unit_required":  "Choose a tracking unit.",
        "vcat.err.bad_number":     "Invalid numeric value.",
        "vcat.err.delete_blocked": "Cannot delete: vehicles or fleets use this category.",

        "cat.bus":        "Bus",
        "cat.minibus":    "Minibus",
        "cat.navette":    "Shuttle",
        "cat.camion_tsf": "TSF Truck",
        "cat.machine_tsf": "TSF Machine",
        "cat.citerne":    "Water tanker",
        "cat.service":    "Service vehicle",
        "cat.autre":      "Other",

        "perm.cat.vehicles":     "Vehicles",
        "perm.cat.operators":    "Operators",
        "perm.cat.entries":      "Entries",
        "perm.cat.maintenance":  "Maintenance",
        "perm.cat.expenses":     "Expenses",
        "perm.cat.reports":      "Reports",
        "perm.cat.alerts":       "Alerts",
        "perm.cat.admin":        "Administration",

        "photo.upload_required":             "A photo of the slip is required.",
        "photo.upload_required_with_reason": "The photo could not be saved, so the entry was not recorded.",
        "photo.err.not_configured":          "Photo storage is not configured on the server — contact your admin.",
        "photo.err.too_large":               "Photo is too large (over 12 MB). Take a new photo or pick a smaller one.",
        "photo.err.bad_format":              "Photo format not supported (likely an iPhone HEIC). Use the camera as JPEG, or pick a JPEG/PNG from the gallery.",
        "photo.err.s3_error":                "Could not reach photo storage — connection problem. Try again when you have better signal.",
        "photo.err.unknown":                 "Photo upload failed — unknown error. Please retry; if it persists, contact your admin.",

        # ── Placeholders: worked examples shown inside empty inputs ──
        "ph.vehicle.code":        "e.g. BUS-001",
        "ph.vehicle.site":        "e.g. Kamsar",
        "ph.vehicle.baseline":    "e.g. 12.5",
        "ph.vehicle.description": "e.g. 45-seat bus used for staff transport",
        "ph.operator.name":       "e.g. Mamadou Diallo",
        "ph.operator.phone":      "e.g. 622 00 00 00",
        "ph.operator.license":    "e.g. GN-2021-004512",
        "ph.operator.notes":      "e.g. Cleared for bus and truck",
        "ph.fleet.name":          "e.g. Zone Nord",
        "ph.fleet.slug":          "e.g. zone-nord (generated if left empty)",
        "ph.fleet.description":   "e.g. Fleet based at the Kamsar site",
        "ph.expense.amount":      "e.g. 250000",
        "ph.expense.liters":      "e.g. 45",
        "ph.expense.supplier":    "e.g. Total Kamsar",
        "ph.expense.description": "e.g. Diesel fill-up before mission",
        "ph.record.cost":         "e.g. 1500000",
        "ph.record.supplier":     "e.g. Garage Central",
        "ph.record.description":  "e.g. Oil change + filter replacement",
        "ph.rule.name":           "e.g. Engine oil change",
        "ph.rule.interval":       "e.g. 5000",
        "ph.rule.warning":        "e.g. 500",
        "ph.vcat.code":           "e.g. BUS",
        "ph.vcat.label":          "e.g. Bus",
        "ph.vcat.baseline":       "e.g. 12.5",
        "ph.vcat.sort":           "e.g. 1",
        "ph.role.name":           "e.g. Fleet supervisor",
        "ph.role.description":    "e.g. Can log and approve the site's entries",
        "ph.user.username":       "e.g. mdiallo",
        "ph.user.full_name":      "e.g. Mamadou Diallo",
        "ph.user.email":          "e.g. mdiallo@zone-equip.com",
        "ph.entry.trips":         "e.g. 3",
        "ph.entry.hours":         "e.g. 7.5",
        "ph.entry.index":         "e.g. 1245.5",
        "ph.entry.km":            "e.g. 120",
        "ph.entry.note":          "e.g. Delayed at loading",
    },
}
