"""French + English translations.

French is the default (target audience: Guinea mining site). Keys follow the
batmex_web convention: dotted namespaces (section.key).

Anything missing from a non-default language falls back through `get_t`'s
chained lookup in app.py.
"""

TRANSLATIONS = {
    # ── French (default) ──────────────────────────────────────────────────
    "fr": {
        # Brand
        "app.title": "Zone Web",
        "app.tagline": "Suivi de flotte",

        # Auth
        "auth.login":             "Connexion",
        "auth.logout":            "Déconnexion",
        "auth.username":          "Nom d'utilisateur",
        "auth.email":             "Courriel",
        "auth.email_optional":    "Courriel (facultatif)",
        "auth.password":          "Mot de passe",
        "auth.sign_in":           "Se connecter",
        "auth.invalid_credentials": "Identifiants invalides.",
        "auth.required":          "Veuillez vous connecter.",

        # Dashboard
        "dash.welcome":   "Bienvenue",
        "dash.super_sub": "Super admin — accès complet à la configuration et à toutes les flottes.",

        # Nav
        "nav.dashboard":            "Tableau de bord",
        "nav.vehicles":             "Véhicules",
        "nav.operators":            "Conducteurs",
        "nav.roster":               "Pointage",
        "nav.daily_entries":        "Saisie quotidienne",
        "nav.maintenance":          "Maintenance",
        "nav.maintenance_records":  "Historique entretien",
        "nav.maintenance_rules":    "Règles d'entretien",
        "nav.alerts":               "Alertes",
        "nav.expenses":             "Dépenses",
        "nav.reports":              "Rapports",
        "nav.approvals":            "Validations en attente",
        "nav.admin":                "Administration",
        "nav.change_password":      "Changer le mot de passe",

        # Password change
        "pw.title":                  "Changement de mot de passe",
        "pw.error.wrong_current":    "Le mot de passe actuel est incorrect.",
        "pw.error.too_short":        "Le nouveau mot de passe doit contenir au moins 6 caractères.",
        "pw.error.no_match":         "Les deux nouveaux mots de passe ne correspondent pas.",
        "pw.success":                "Mot de passe mis à jour.",
        "form.current_password":     "Mot de passe actuel",
        "form.new_password":         "Nouveau mot de passe",
        "form.confirm_password":     "Confirmer le nouveau mot de passe",
        "form.update_password":      "Mettre à jour le mot de passe",

        # Admin
        "admin.users":      "Utilisateurs",
        "admin.fleets":     "Flottes",
        "admin.roles":      "Rôles",
        "admin.categories": "Catégories de véhicules",
        "admin.settings":   "Paramètres",
        "admin.audit_log":  "Journal d'audit",

        # Fleets
        "fleet.new":            "Nouvelle flotte",
        "fleet.edit":           "Modifier la flotte",
        "fleet.name":           "Nom",
        "fleet.name_hint":      "ex. Transport personnel",
        "fleet.slug":           "Identifiant (slug)",
        "fleet.slug_hint":      "généré automatiquement si laissé vide",
        "fleet.description":    "Description",
        "fleet.categories":     "Catégories de véhicules",
        "fleet.vehicles":       "Véhicules",
        "fleet.users":          "Utilisateurs",
        "fleet.empty":          "Aucune flotte pour le moment.",
        "fleet.created":        "Flotte créée.",
        "fleet.updated":        "Flotte mise à jour.",
        "fleet.deleted":        "Flotte supprimée.",
        "fleet.delete_confirm": "Supprimer cette flotte ?",
        "fleet.err.name_required": "Le nom est obligatoire.",
        "fleet.err.name_taken":    "Une flotte porte déjà ce nom.",
        "fleet.err.slug_taken":    "Cet identifiant (slug) est déjà utilisé.",
        "fleet.err.delete_blocked": "Impossible de supprimer : des véhicules, conducteurs ou utilisateurs sont encore rattachés à cette flotte.",

        # Vehicles
        "vehicle.new":            "Nouveau véhicule",
        "vehicle.edit":           "Modifier le véhicule",
        "vehicle.all":            "Tous",
        "vehicle.code":           "Code / Immatriculation",
        "vehicle.category":       "Catégorie",
        "vehicle.fleet":          "Flotte",
        "vehicle.site":           "Site",
        "vehicle.description":    "Description",
        "vehicle.baseline":       "Consommation de référence",
        "vehicle.baseline_override": "Consommation (L/unité)",
        "vehicle.baseline_hint":  "Laisser vide pour utiliser la valeur par défaut de la catégorie.",
        "vehicle.cost_override":  "Coût par unité (GNF)",
        "vehicle.cost_hint":      "Laisser vide pour utiliser la valeur par défaut de la catégorie.",
        "vehicle.operator_morning": "Conducteur (matin)",
        "vehicle.operator_evening": "Conducteur (soir)",
        "vehicle.active":         "Actif",
        "vehicle.inactive":       "Inactif",
        "vehicle.is_active":      "Véhicule actif",
        "vehicle.status":         "Statut",
        "vehicle.from_category":  "valeur de la catégorie",
        "vehicle.empty":          "Aucun véhicule pour le moment.",
        "vehicle.created":        "Véhicule créé.",
        "vehicle.updated":        "Véhicule mis à jour.",
        "vehicle.deleted":        "Véhicule supprimé.",
        "vehicle.submitted":      "Modification soumise pour validation.",
        "vehicle.delete_confirm": "Supprimer ce véhicule ?",
        "vehicle.err.code_required":     "Le code du véhicule est obligatoire.",
        "vehicle.err.fleet_required":    "Veuillez choisir une flotte.",
        "vehicle.err.category_required": "Veuillez choisir une catégorie.",
        "vehicle.err.code_taken":        "Ce code de véhicule existe déjà.",
        "vehicle.err.cat_not_in_fleet":  "Cette catégorie n'appartient pas à la flotte choisie.",
        "vehicle.err.bad_number":        "Valeur numérique invalide.",
        "vehicle.err.delete_blocked":    "Impossible de supprimer : des saisies, entretiens ou dépenses sont rattachés à ce véhicule.",

        # Operators (drivers)
        "operator.new":            "Nouveau conducteur",
        "operator.edit":           "Modifier le conducteur",
        "operator.all":            "Tous",
        "operator.name":           "Nom",
        "operator.fleet":          "Flotte",
        "operator.phone":          "Téléphone",
        "operator.license":        "N° de permis",
        "operator.notes":          "Notes",
        "operator.active":         "Actif",
        "operator.inactive":       "Inactif",
        "operator.is_active":      "Conducteur actif",
        "operator.status":         "Statut",
        "operator.empty":          "Aucun conducteur pour le moment.",
        "operator.created":        "Conducteur créé.",
        "operator.updated":        "Conducteur mis à jour.",
        "operator.deleted":        "Conducteur supprimé.",
        "operator.submitted":      "Modification soumise pour validation.",
        "operator.delete_confirm": "Supprimer ce conducteur ?",
        "operator.err.name_required":  "Le nom est obligatoire.",
        "operator.err.fleet_required": "Veuillez choisir une flotte.",
        "operator.err.name_taken":     "Un conducteur porte déjà ce nom dans cette flotte.",

        # Daily entries
        "entry.new":            "Nouvelle saisie",
        "entry.edit":           "Modifier la saisie",
        "entry.add":            "Ajouter",
        "entry.vehicle":        "Véhicule",
        "entry.date":           "Date",
        "entry.trips":          "Voyages",
        "entry.hours":          "Heures",
        "entry.fuel":           "Carburant (L)",
        "entry.km":             "Kilométrage",
        "entry.operator":       "Conducteur",
        "entry.note":           "Note",
        "entry.activity":       "Activité",
        "entry.all_vehicles":   "Tous les véhicules",
        "entry.clear":          "Réinitialiser",
        "entry.empty":          "Aucune saisie pour le moment.",
        "entry.created":        "Saisie enregistrée.",
        "entry.updated":        "Saisie mise à jour.",
        "entry.deleted":        "Saisie supprimée.",
        "entry.submitted":      "Saisie soumise pour validation.",
        "entry.delete_confirm": "Supprimer cette saisie ?",
        "entry.err.vehicle_required": "Veuillez choisir un véhicule.",
        "entry.err.date_required":    "Date invalide.",
        "entry.err.bad_number":       "Valeur numérique invalide.",

        # Roster (pointage)
        "roster.prev_day":   "Jour précédent",
        "roster.next_day":   "Jour suivant",
        "roster.done":       "faits",
        "roster.pending":    "en attente",
        "roster.tap_to_log": "Appuyer pour saisir",
        "roster.no_vehicles": "Aucun véhicule actif dans cette flotte.",
        "roster.no_fleet":   "Aucune flotte accessible. Demandez l'accès à une flotte.",

        # Expenses
        "expense.new":            "Nouvelle dépense",
        "expense.edit":           "Modifier la dépense",
        "expense.add":            "Ajouter",
        "expense.all":            "Toutes",
        "expense.category":       "Catégorie",
        "expense.date":           "Date",
        "expense.fleet":          "Flotte",
        "expense.vehicle":        "Véhicule",
        "expense.fleet_wide":     "Dépense de flotte",
        "expense.target":         "Véhicule / Flotte",
        "expense.amount":         "Montant (GNF)",
        "expense.liters":         "Litres",
        "expense.supplier":       "Fournisseur",
        "expense.description":    "Description",
        "expense.total":          "Total : ",
        "expense.count":          "dépenses",
        "expense.empty":          "Aucune dépense pour le moment.",
        "expense.created":        "Dépense enregistrée.",
        "expense.updated":        "Dépense mise à jour.",
        "expense.deleted":        "Dépense supprimée.",
        "expense.submitted":      "Dépense soumise pour validation.",
        "expense.delete_confirm": "Supprimer cette dépense ?",
        "expense.err.category_required": "Veuillez choisir une catégorie.",
        "expense.err.fleet_required":    "Veuillez choisir une flotte.",
        "expense.err.vehicle_fleet":     "Le véhicule n'appartient pas à la flotte choisie.",
        "expense.err.date_required":     "Date invalide.",
        "expense.err.amount_required":   "Montant invalide.",
        "expense.err.bad_number":        "Valeur numérique invalide.",
        "expense.cat.fuel":       "Carburant",
        "expense.cat.vidange":    "Vidange",
        "expense.cat.filtre":     "Filtres",
        "expense.cat.pneus":      "Pneus",
        "expense.cat.reparation": "Réparation",
        "expense.cat.piece":      "Pièces détachées",
        "expense.cat.assurance":  "Assurance",
        "expense.cat.accident":   "Accident",
        "expense.cat.lavage":     "Lavage",
        "expense.cat.agent":      "Frais d'agent",
        "expense.cat.autre":      "Autre",

        # Maintenance — rules
        "maint.rule_new":        "Nouvelle règle",
        "maint.rule_edit":       "Modifier la règle",
        "maint.rule_name":       "Nom de la règle",
        "maint.service_type":    "Type d'entretien",
        "maint.rule_type":       "Déclencheur",
        "maint.severity":        "Gravité",
        "maint.interval":        "Intervalle",
        "maint.interval_hint":   "km, heures ou jours selon le type.",
        "maint.advance_warning": "Préavis (avant échéance)",
        "maint.target":          "Cible",
        "maint.rule_active":     "Règle active",
        "maint.days":            "jours",
        "maint.ruletype.km_recurring":    "Récurrent (km)",
        "maint.ruletype.hours_recurring": "Récurrent (heures)",
        "maint.ruletype.time_recurring":  "Récurrent (temps)",
        "maint.sev.info":        "Info",
        "maint.sev.warning":     "Avertissement",
        "maint.sev.critical":    "Critique",
        "maint.target.all":      "Tous les véhicules",
        "maint.target.fleet":    "Flotte",
        "maint.target.category": "Catégorie",
        "maint.target.vehicle":  "Véhicule",
        "maint.rules_empty":     "Aucune règle d'entretien.",
        "maint.rule_created":    "Règle créée.",
        "maint.rule_updated":    "Règle mise à jour.",
        "maint.rule_deleted":    "Règle supprimée.",
        "maint.rule_delete_confirm": "Supprimer cette règle et ses alertes ?",
        # Maintenance — records
        "maint.record_new":      "Nouvel entretien",
        "maint.record_edit":     "Modifier l'entretien",
        "maint.vehicle":         "Véhicule",
        "maint.record_type":     "Type d'entretien",
        "maint.date":            "Date",
        "maint.cost":            "Coût (GNF)",
        "maint.kilometers_at":   "Km au compteur",
        "maint.hours_at":        "Heures au compteur",
        "maint.at":              "Compteur",
        "maint.supplier":        "Fournisseur",
        "maint.description":     "Description",
        "maint.all_vehicles":    "Tous les véhicules",
        "maint.records_empty":   "Aucun entretien enregistré.",
        "maint.record_created":  "Entretien enregistré.",
        "maint.record_updated":  "Entretien mis à jour.",
        "maint.record_deleted":  "Entretien supprimé.",
        "maint.record_submitted": "Entretien soumis pour validation.",
        "maint.record_delete_confirm": "Supprimer cet entretien ?",
        "maint.rtype.oil_change": "Vidange",
        "maint.rtype.filter":    "Filtres",
        "maint.rtype.tires":     "Pneus",
        "maint.rtype.brakes":    "Freins",
        "maint.rtype.repair":    "Réparation",
        "maint.rtype.parts":     "Pièces détachées",
        "maint.rtype.revision":  "Révision",
        "maint.rtype.other":     "Autre",
        # Alerts
        "maint.alerts.active":   "Actives",
        "maint.alerts.resolved": "Résolues",
        "maint.alerts.dismissed": "Ignorées",
        "maint.alerts_empty":    "Aucune alerte. Tout est à jour.",
        "maint.log_service":     "Enregistrer l'entretien",
        "maint.snooze":          "Reporter",
        "maint.resolve":         "Résoudre",
        "maint.dismiss":         "Ignorer",
        "maint.snoozed_until":   "reporté au",
        "maint.status.open":     "Ouverte",
        "maint.status.snoozed":  "Reportée",
        "maint.status.resolved": "Résolue",
        "maint.status.dismissed": "Ignorée",
        "maint.alert_snoozed":   "Alerte reportée.",
        "maint.alert_resolved":  "Alerte résolue.",
        "maint.alert_dismissed": "Alerte ignorée.",
        # Maintenance errors
        "maint.err.name_required":     "Le nom est obligatoire.",
        "maint.err.type_required":     "Veuillez choisir un déclencheur.",
        "maint.err.service_type_required": "Veuillez choisir un type d'entretien.",
        "maint.err.interval_required": "Intervalle invalide.",
        "maint.err.bad_number":        "Valeur numérique invalide.",
        "maint.err.target":            "Cible invalide.",
        "maint.err.vehicle_required":  "Veuillez choisir un véhicule.",
        "maint.err.rtype_required":    "Veuillez choisir un type d'entretien.",
        "maint.err.date_required":     "Date invalide.",

        # Units & common
        "unit.trips": "voyage",
        "unit.hours": "heure",
        "common.coming_soon": "Bientôt disponible",
        "btn.back": "Retour",
        "btn.view": "Voir",

        # Roles
        "role.super_admin": "Super admin",
        "role.user":        "Utilisateur",

        # Errors
        "error.forbidden":  "Accès refusé",
        "error.not_found":  "Page introuvable",

        # Common buttons / labels
        "btn.save":   "Enregistrer",
        "btn.cancel": "Annuler",
        "btn.edit":   "Modifier",
        "btn.delete": "Supprimer",
        "btn.new":    "Nouveau",
        "btn.approve": "Approuver",
        "btn.reject":  "Refuser",
        "btn.dismiss": "Ignorer",
        "btn.submit_for_approval": "Soumettre pour validation",

        # Forms
        "form.optional": "Facultatif",
        "form.required": "Obligatoire",
        "form.select":   "Sélectionner…",
        "form.search":   "Rechercher…",

        # Vehicle categories (master list labels for UI)
        "cat.bus":        "Bus",
        "cat.minibus":    "Minibus",
        "cat.navette":    "Navette",
        "cat.camion_tsf": "Camion TSF",
        "cat.machine_tsf": "Machine TSF",
        "cat.citerne":    "Citerne",
        "cat.service":    "Véhicule de service",
        "cat.autre":      "Autre",

        # Permissions categories (for the role grid)
        "perm.cat.vehicles":     "Véhicules",
        "perm.cat.operators":    "Conducteurs",
        "perm.cat.entries":      "Saisies",
        "perm.cat.maintenance":  "Maintenance",
        "perm.cat.expenses":     "Dépenses",
        "perm.cat.reports":      "Rapports",
        "perm.cat.alerts":       "Alertes",
        "perm.cat.admin":        "Administration",

        # Photo errors (carried over from batmex)
        "photo.upload_required":             "Une photo du bon est obligatoire.",
        "photo.upload_required_with_reason": "La photo n'a pas pu être enregistrée, donc la saisie n'a pas été sauvegardée.",
        "photo.err.not_configured":          "Le stockage des photos n'est pas configuré sur le serveur — contacte l'admin.",
        "photo.err.too_large":               "Photo trop volumineuse (plus de 12 Mo). Reprends une photo ou choisis-en une plus petite.",
        "photo.err.bad_format":              "Format de photo non supporté (souvent un HEIC iPhone). Utilise l'appareil photo en JPEG, ou choisis une JPEG/PNG depuis la galerie.",
        "photo.err.s3_error":                "Impossible de joindre le stockage photo — problème de connexion. Réessaie quand le réseau est meilleur.",
        "photo.err.unknown":                 "Échec de l'envoi de la photo — erreur inconnue. Réessaie ; si ça persiste, contacte l'admin.",
    },

    # ── English ───────────────────────────────────────────────────────────
    "en": {
        "app.title": "Zone Web",
        "app.tagline": "Fleet tracking",

        "auth.login":             "Login",
        "auth.logout":            "Log out",
        "auth.username":          "Username",
        "auth.email":             "Email",
        "auth.email_optional":    "Email (optional)",
        "auth.password":          "Password",
        "auth.sign_in":           "Sign in",
        "auth.invalid_credentials": "Invalid credentials.",
        "auth.required":          "Please log in.",

        "dash.welcome":   "Welcome",
        "dash.super_sub": "Super admin — full access to configuration and all fleets.",

        "nav.dashboard":            "Dashboard",
        "nav.vehicles":             "Vehicles",
        "nav.operators":            "Operators",
        "nav.roster":               "Roster",
        "nav.daily_entries":        "Daily entries",
        "nav.maintenance":          "Maintenance",
        "nav.maintenance_records":  "Maintenance history",
        "nav.maintenance_rules":    "Maintenance rules",
        "nav.alerts":               "Alerts",
        "nav.expenses":             "Expenses",
        "nav.reports":              "Reports",
        "nav.approvals":            "Pending approvals",
        "nav.admin":                "Administration",
        "nav.change_password":      "Change password",

        # Password change
        "pw.title":                  "Change password",
        "pw.error.wrong_current":    "Current password is incorrect.",
        "pw.error.too_short":        "New password must be at least 6 characters.",
        "pw.error.no_match":         "The two new passwords do not match.",
        "pw.success":                "Password updated.",
        "form.current_password":     "Current password",
        "form.new_password":         "New password",
        "form.confirm_password":     "Confirm new password",
        "form.update_password":      "Update password",

        "admin.users":      "Users",
        "admin.fleets":     "Fleets",
        "admin.roles":      "Roles",
        "admin.categories": "Vehicle categories",
        "admin.settings":   "Settings",
        "admin.audit_log":  "Audit log",

        # Fleets
        "fleet.new":            "New fleet",
        "fleet.edit":           "Edit fleet",
        "fleet.name":           "Name",
        "fleet.name_hint":      "e.g. Staff transport",
        "fleet.slug":           "Slug",
        "fleet.slug_hint":      "auto-generated if left blank",
        "fleet.description":    "Description",
        "fleet.categories":     "Vehicle categories",
        "fleet.vehicles":       "Vehicles",
        "fleet.users":          "Users",
        "fleet.empty":          "No fleets yet.",
        "fleet.created":        "Fleet created.",
        "fleet.updated":        "Fleet updated.",
        "fleet.deleted":        "Fleet deleted.",
        "fleet.delete_confirm": "Delete this fleet?",
        "fleet.err.name_required": "Name is required.",
        "fleet.err.name_taken":    "A fleet with this name already exists.",
        "fleet.err.slug_taken":    "That slug is already in use.",
        "fleet.err.delete_blocked": "Cannot delete: vehicles, operators or users are still attached to this fleet.",

        # Vehicles
        "vehicle.new":            "New vehicle",
        "vehicle.edit":           "Edit vehicle",
        "vehicle.all":            "All",
        "vehicle.code":           "Code / Plate",
        "vehicle.category":       "Category",
        "vehicle.fleet":          "Fleet",
        "vehicle.site":           "Site",
        "vehicle.description":    "Description",
        "vehicle.baseline":       "Baseline consumption",
        "vehicle.baseline_override": "Consumption (L/unit)",
        "vehicle.baseline_hint":  "Leave blank to use the category default.",
        "vehicle.cost_override":  "Cost per unit (GNF)",
        "vehicle.cost_hint":      "Leave blank to use the category default.",
        "vehicle.operator_morning": "Driver (morning)",
        "vehicle.operator_evening": "Driver (evening)",
        "vehicle.active":         "Active",
        "vehicle.inactive":       "Inactive",
        "vehicle.is_active":      "Vehicle active",
        "vehicle.status":         "Status",
        "vehicle.from_category":  "category default",
        "vehicle.empty":          "No vehicles yet.",
        "vehicle.created":        "Vehicle created.",
        "vehicle.updated":        "Vehicle updated.",
        "vehicle.deleted":        "Vehicle deleted.",
        "vehicle.submitted":      "Change submitted for approval.",
        "vehicle.delete_confirm": "Delete this vehicle?",
        "vehicle.err.code_required":     "Vehicle code is required.",
        "vehicle.err.fleet_required":    "Please choose a fleet.",
        "vehicle.err.category_required": "Please choose a category.",
        "vehicle.err.code_taken":        "A vehicle with this code already exists.",
        "vehicle.err.cat_not_in_fleet":  "That category does not belong to the chosen fleet.",
        "vehicle.err.bad_number":        "Invalid numeric value.",
        "vehicle.err.delete_blocked":    "Cannot delete: entries, maintenance or expenses are attached to this vehicle.",

        # Operators (drivers)
        "operator.new":            "New operator",
        "operator.edit":           "Edit operator",
        "operator.all":            "All",
        "operator.name":           "Name",
        "operator.fleet":          "Fleet",
        "operator.phone":          "Phone",
        "operator.license":        "Licence no.",
        "operator.notes":          "Notes",
        "operator.active":         "Active",
        "operator.inactive":       "Inactive",
        "operator.is_active":      "Operator active",
        "operator.status":         "Status",
        "operator.empty":          "No operators yet.",
        "operator.created":        "Operator created.",
        "operator.updated":        "Operator updated.",
        "operator.deleted":        "Operator deleted.",
        "operator.submitted":      "Change submitted for approval.",
        "operator.delete_confirm": "Delete this operator?",
        "operator.err.name_required":  "Name is required.",
        "operator.err.fleet_required": "Please choose a fleet.",
        "operator.err.name_taken":     "An operator with this name already exists in this fleet.",

        # Daily entries
        "entry.new":            "New entry",
        "entry.edit":           "Edit entry",
        "entry.add":            "Add",
        "entry.vehicle":        "Vehicle",
        "entry.date":           "Date",
        "entry.trips":          "Trips",
        "entry.hours":          "Hours",
        "entry.fuel":           "Fuel (L)",
        "entry.km":             "Kilometers",
        "entry.operator":       "Driver",
        "entry.note":           "Note",
        "entry.activity":       "Activity",
        "entry.all_vehicles":   "All vehicles",
        "entry.clear":          "Clear",
        "entry.empty":          "No entries yet.",
        "entry.created":        "Entry saved.",
        "entry.updated":        "Entry updated.",
        "entry.deleted":        "Entry deleted.",
        "entry.submitted":      "Entry submitted for approval.",
        "entry.delete_confirm": "Delete this entry?",
        "entry.err.vehicle_required": "Please choose a vehicle.",
        "entry.err.date_required":    "Invalid date.",
        "entry.err.bad_number":       "Invalid numeric value.",

        # Roster
        "roster.prev_day":   "Previous day",
        "roster.next_day":   "Next day",
        "roster.done":       "done",
        "roster.pending":    "pending",
        "roster.tap_to_log": "Tap to log",
        "roster.no_vehicles": "No active vehicles in this fleet.",
        "roster.no_fleet":   "No accessible fleet. Ask for fleet access.",

        # Expenses
        "expense.new":            "New expense",
        "expense.edit":           "Edit expense",
        "expense.add":            "Add",
        "expense.all":            "All",
        "expense.category":       "Category",
        "expense.date":           "Date",
        "expense.fleet":          "Fleet",
        "expense.vehicle":        "Vehicle",
        "expense.fleet_wide":     "Fleet-wide",
        "expense.target":         "Vehicle / Fleet",
        "expense.amount":         "Amount (GNF)",
        "expense.liters":         "Litres",
        "expense.supplier":       "Supplier",
        "expense.description":    "Description",
        "expense.total":          "Total: ",
        "expense.count":          "expenses",
        "expense.empty":          "No expenses yet.",
        "expense.created":        "Expense saved.",
        "expense.updated":        "Expense updated.",
        "expense.deleted":        "Expense deleted.",
        "expense.submitted":      "Expense submitted for approval.",
        "expense.delete_confirm": "Delete this expense?",
        "expense.err.category_required": "Please choose a category.",
        "expense.err.fleet_required":    "Please choose a fleet.",
        "expense.err.vehicle_fleet":     "The vehicle does not belong to the chosen fleet.",
        "expense.err.date_required":     "Invalid date.",
        "expense.err.amount_required":   "Invalid amount.",
        "expense.err.bad_number":        "Invalid numeric value.",
        "expense.cat.fuel":       "Fuel",
        "expense.cat.vidange":    "Oil change",
        "expense.cat.filtre":     "Filters",
        "expense.cat.pneus":      "Tyres",
        "expense.cat.reparation": "Repair",
        "expense.cat.piece":      "Spare parts",
        "expense.cat.assurance":  "Insurance",
        "expense.cat.accident":   "Accident",
        "expense.cat.lavage":     "Washing",
        "expense.cat.agent":      "Agent fees",
        "expense.cat.autre":      "Other",

        # Maintenance — rules
        "maint.rule_new":        "New rule",
        "maint.rule_edit":       "Edit rule",
        "maint.rule_name":       "Rule name",
        "maint.service_type":    "Service type",
        "maint.rule_type":       "Trigger",
        "maint.severity":        "Severity",
        "maint.interval":        "Interval",
        "maint.interval_hint":   "km, hours or days depending on the type.",
        "maint.advance_warning": "Advance warning",
        "maint.target":          "Target",
        "maint.rule_active":     "Rule active",
        "maint.days":            "days",
        "maint.ruletype.km_recurring":    "Recurring (km)",
        "maint.ruletype.hours_recurring": "Recurring (hours)",
        "maint.ruletype.time_recurring":  "Recurring (time)",
        "maint.sev.info":        "Info",
        "maint.sev.warning":     "Warning",
        "maint.sev.critical":    "Critical",
        "maint.target.all":      "All vehicles",
        "maint.target.fleet":    "Fleet",
        "maint.target.category": "Category",
        "maint.target.vehicle":  "Vehicle",
        "maint.rules_empty":     "No maintenance rules.",
        "maint.rule_created":    "Rule created.",
        "maint.rule_updated":    "Rule updated.",
        "maint.rule_deleted":    "Rule deleted.",
        "maint.rule_delete_confirm": "Delete this rule and its alerts?",
        # Maintenance — records
        "maint.record_new":      "New service",
        "maint.record_edit":     "Edit service",
        "maint.vehicle":         "Vehicle",
        "maint.record_type":     "Service type",
        "maint.date":            "Date",
        "maint.cost":            "Cost (GNF)",
        "maint.kilometers_at":   "Odometer (km)",
        "maint.hours_at":        "Hours meter",
        "maint.at":              "Meter",
        "maint.supplier":        "Supplier",
        "maint.description":     "Description",
        "maint.all_vehicles":    "All vehicles",
        "maint.records_empty":   "No service records.",
        "maint.record_created":  "Service recorded.",
        "maint.record_updated":  "Service updated.",
        "maint.record_deleted":  "Service deleted.",
        "maint.record_submitted": "Service submitted for approval.",
        "maint.record_delete_confirm": "Delete this service record?",
        "maint.rtype.oil_change": "Oil change",
        "maint.rtype.filter":    "Filters",
        "maint.rtype.tires":     "Tyres",
        "maint.rtype.brakes":    "Brakes",
        "maint.rtype.repair":    "Repair",
        "maint.rtype.parts":     "Spare parts",
        "maint.rtype.revision":  "Service",
        "maint.rtype.other":     "Other",
        # Alerts
        "maint.alerts.active":   "Active",
        "maint.alerts.resolved": "Resolved",
        "maint.alerts.dismissed": "Dismissed",
        "maint.alerts_empty":    "No alerts. All up to date.",
        "maint.log_service":     "Log service",
        "maint.snooze":          "Snooze",
        "maint.resolve":         "Resolve",
        "maint.dismiss":         "Dismiss",
        "maint.snoozed_until":   "snoozed until",
        "maint.status.open":     "Open",
        "maint.status.snoozed":  "Snoozed",
        "maint.status.resolved": "Resolved",
        "maint.status.dismissed": "Dismissed",
        "maint.alert_snoozed":   "Alert snoozed.",
        "maint.alert_resolved":  "Alert resolved.",
        "maint.alert_dismissed": "Alert dismissed.",
        # Maintenance errors
        "maint.err.name_required":     "Name is required.",
        "maint.err.type_required":     "Please choose a trigger.",
        "maint.err.service_type_required": "Please choose a service type.",
        "maint.err.interval_required": "Invalid interval.",
        "maint.err.bad_number":        "Invalid numeric value.",
        "maint.err.target":            "Invalid target.",
        "maint.err.vehicle_required":  "Please choose a vehicle.",
        "maint.err.rtype_required":    "Please choose a service type.",
        "maint.err.date_required":     "Invalid date.",

        # Units & common
        "unit.trips": "trip",
        "unit.hours": "hour",
        "common.coming_soon": "Coming soon",
        "btn.back": "Back",
        "btn.view": "View",

        "role.super_admin": "Super admin",
        "role.user":        "User",

        "error.forbidden":  "Forbidden",
        "error.not_found":  "Not found",

        "btn.save":   "Save",
        "btn.cancel": "Cancel",
        "btn.edit":   "Edit",
        "btn.delete": "Delete",
        "btn.new":    "New",
        "btn.approve": "Approve",
        "btn.reject":  "Reject",
        "btn.dismiss": "Dismiss",
        "btn.submit_for_approval": "Submit for approval",

        "form.optional": "Optional",
        "form.required": "Required",
        "form.select":   "Select…",
        "form.search":   "Search…",

        "cat.bus":        "Bus",
        "cat.minibus":    "Minibus",
        "cat.navette":    "Shuttle",
        "cat.camion_tsf": "TSF Truck",
        "cat.machine_tsf": "TSF Machine",
        "cat.citerne":    "Water tanker",
        "cat.service":    "Service vehicle",
        "cat.autre":      "Other",

        "perm.cat.vehicles":     "Vehicles",
        "perm.cat.operators":    "Operators",
        "perm.cat.entries":      "Entries",
        "perm.cat.maintenance":  "Maintenance",
        "perm.cat.expenses":     "Expenses",
        "perm.cat.reports":      "Reports",
        "perm.cat.alerts":       "Alerts",
        "perm.cat.admin":        "Administration",

        "photo.upload_required":             "A photo of the slip is required.",
        "photo.upload_required_with_reason": "The photo could not be saved, so the entry was not recorded.",
        "photo.err.not_configured":          "Photo storage is not configured on the server — contact your admin.",
        "photo.err.too_large":               "Photo is too large (over 12 MB). Take a new photo or pick a smaller one.",
        "photo.err.bad_format":              "Photo format not supported (likely an iPhone HEIC). Use the camera as JPEG, or pick a JPEG/PNG from the gallery.",
        "photo.err.s3_error":                "Could not reach photo storage — connection problem. Try again when you have better signal.",
        "photo.err.unknown":                 "Photo upload failed — unknown error. Please retry; if it persists, contact your admin.",
    },
}
