"""Add operators table

Revision ID: 1da4b139d7c2
Revises: e887f3316c28
Create Date: 2026-06-15 23:19:55.626138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da4b139d7c2'
down_revision = 'e887f3316c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fleet_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('license_number', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fleet_id'], ['fleets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fleet_id', 'name', name='uq_operators_fleet_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operators')
    # ### end Alembic commands ###
